### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by iranmdl** [AstraZeneca-NGS/VarDictJava#100]
Hello!

 I'm trying to run `VarDict` java version using GRCh38 genome, the tool works fine with GRCh37. This is the command I'm using:

`../bin/VarDict -G Homo_sapiens_assembly38_noalt.fasta -f 0.01 -N tumor_R1_sorted_dedup_recab_realigned -b "/BAMs/tumor_R1_sorted_dedup_recab_realigned.bam|/BAMs/WT_R1_sorted_dedup_recab_realigned.bam" -th 8 -C -c 1 -S 2 -E 3 -g 4 bed_files/covered_segments_GRCh38.bed | testsomatic.R | var2vcf_paired.pl -P 0.9 -N "tumor_R1_sorted_dedup_recab_realigned|WT_R1_sorted_dedup_recab_realigned" -f 0.01 > vardict.vcf
`
And this is the **error** I get:

```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.astrazeneca.vardict.VarDict.somaticParallel(VarDict.java:347)
	at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:260)
	at com.astrazeneca.vardict.VarDict.start(VarDict.java:74)
	at com.astrazeneca.vardict.Main.run(Main.java:138)
	at com.astrazeneca.vardict.Main.main(Main.java:25)
Caused by: java.lang.NullPointerException
	at com.astrazeneca.vardict.VarDict.parseSAM(VarDict.java:1624)
	at com.astrazeneca.vardict.VarDict.toVars(VarDict.java:2642)
	at com.astrazeneca.vardict.VarDict$ToVarsWorker.call(VarDict.java:5397)
	at com.astrazeneca.vardict.VarDict$SomdictWorker.call(VarDict.java:5418)
	at com.astrazeneca.vardict.VarDict$SomdictWorker.call(VarDict.java:5402)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Any help would be appreciated,
Thank you :)

**Comment by iranmdl** [comment]
Hello!
Any news about this? :-)
