### ISSUE TITLE
CIGAR string parsing issues with alignments from bwa mem 0.7.12

### ISSUE THREAD

**Issue by chapmanb** [AstraZeneca-NGS/VarDictJava#14]
Viktor and Zaal;
While running additional whole genome testing with VarDictJava, we ran into two issues parsing
CIGAR strings. These are both with alignment output from the latest bwa (bwa mem 0.7.12).

I put together a reproducible test case here with the two failures (and also the VarDict perl comparisons). You should only need to adjust the path to the GRCh37 reference genome to run the shell script:

https://s3.amazonaws.com/chapmanb/az/cigar_string_issues.tar.gz

The first issue looks related to #11. VarDict finished cleanly on this small
region (with no calls) while VarDictJava errors out with:
```
Exception in thread "main" java.lang.IllegalArgumentException: Malformed CIGAR string: 60S-1M1I25M15S
  at htsjdk.samtools.TextCigarCodec.decode(TextCigarCodec.java:69)
  at com.astrazeneca.vardict.VarDict.parseSAM(VarDict.java:1533)
  at com.astrazeneca.vardict.VarDict.toVars(VarDict.java:2515)
  at com.astrazeneca.vardict.VarDict.vardictNotParallel(VarDict.java:303)
  at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:256)
  at com.astrazeneca.vardict.VarDict.start(VarDict.java:52)
  at com.astrazeneca.vardict.Main.run(Main.java:137)
  at com.astrazeneca.vardict.Main.main(Main.java:24)
```
For the second issue VarDict raises a lot of Perl errors but finished (again
without any output), while VarDictJava errors out with:
```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
  at java.lang.String.charAt(String.java:658)
  at com.astrazeneca.vardict.VarDict.modifyCigar(VarDict.java:6065)
  at com.astrazeneca.vardict.VarDict.parseSAM(VarDict.java:1529)
  at com.astrazeneca.vardict.VarDict.toVars(VarDict.java:2515)
  at com.astrazeneca.vardict.VarDict.vardictNotParallel(VarDict.java:303)
  at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:256)
  at com.astrazeneca.vardict.VarDict.start(VarDict.java:52)
  at com.astrazeneca.vardict.Main.run(Main.java:137)
  at com.astrazeneca.vardict.Main.main(Main.java:24)
```
Both of these may be problematic CIGAR strings but it would be great if VarDictJava could cleanly handle them and continue.

Thanks much for all the work, please let me know if any other information would be helpful.

**Comment by borodini** [comment]
Please verify last VarDictJava release: https://github.com/AstraZeneca-NGS/VarDictJava/releases/tag/v1.3.0 There is a hope that the issues are fixed

**Comment by zhongwulai** [comment]
Brad, it's likely you're not using the latest version.  My test of Perl version didn't produce any warning, and no calls.

**Comment by chapmanb** [comment]
Thanks so much for the new release and quick responses. Apologies, I was unlucky to be debugging this right before the latest Java release (and updating VarDict to match). Things do work cleanly with the test case using the updated versions. Great work on anticipating my report. Thanks again.
