### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by Amao123** [AstraZeneca-NGS/VarDictJava#175]
VarDict -G /Users/cici/test/reference/genome/hg19/index/hg19.fa -f 0.01 -N S2 -b S2.clipped.bam -z -c 1 -S 2 -E 3 -g 4 -th 4 S2.bed > S2.snp

java.util.concurrent.ExecutionException: java.lang.NumberFormatException: null
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.astrazeneca.vardict.VarDict.vardictParallel(VarDict.java:354)
	at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:319)
	at com.astrazeneca.vardict.VarDict.start(VarDict.java:76)
	at com.astrazeneca.vardict.Main.main(Main.java:35)
Caused by: java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.astrazeneca.vardict.Utils.toInt(Utils.java:91)
	at com.astrazeneca.vardict.modules.StructuralVariantsProcessor.prepareSVStructuresForAnalysis(StructuralVariantsProcessor.java:87)
	at com.astrazeneca.vardict.modules.SAMFileParser.parseSAM(SAMFileParser.java:312)
	at com.astrazeneca.vardict.modules.ToVarsBuilder.toVars(ToVarsBuilder.java:69)
	at com.astrazeneca.vardict.VarDict$VardictWorker.call(VarDict.java:1044)
	at com.astrazeneca.vardict.VarDict$VardictWorker.call(VarDict.java:1019)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Excuse me? How to solve this problem?

**Comment by PolinaBevad** [comment]
@Amao123, hello!
Sorry that you have this issue!

If you don't need structural variants in this run, you can re-run the sample with option -U and the error must disappear. 
We will fix the error, I guess I found where it appears, but could you provide a small part of BAM file with a region, where the error appears? If possible, we would like to use it as a test case.

**Comment by ruslan-abasov** [comment]
Hi!
I have similar?but slighty different problem.
VarDict -G genome.fa -N sample -b sample.bam -c 1 -S 2 -E 3 -g 4 my_bed.bed 

Exception in thread "main" java.lang.NumberFormatException: For input string: "24,9"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at com.astrazeneca.vardict.Utils.roundHalfEven(Utils.java:102)
	at com.astrazeneca.vardict.modules.ToVarsBuilder.toVars(ToVarsBuilder.java:156)
	at com.astrazeneca.vardict.VarDict.vardictNotParallel(VarDict.java:372)
	at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:317)
	at com.astrazeneca.vardict.VarDict.start(VarDict.java:76)
	at com.astrazeneca.vardict.Main.main(Main.java:35)

But for non-java version this command works.

**Comment by PolinaBevad** [comment]
@Amao123, hello!
I will close the issue, the fix is already merged in master and will be included in the future release. 
You can build the new version yourself if you want to use it before release, as described here: https://github.com/AstraZeneca-NGS/VarDictJava#compiling

**Comment by LeilyR** [comment]
I have the same issue as @ruslan-abasov. I have already opened an issue [[https://github.com/AstraZeneca-NGS/VarDict](https://github.com/AstraZeneca-NGS/VarDict#)](https://github.com/AstraZeneca-NGS/VarDict/issues/177)
my locale setting is fine (EN-US) and I can run vardict successfully on their test data. My guess is that there is something about my bam file that it doesnot like it. I shared a few line of my bam file in the issue i repotted. 
@ruslan-abasov I wonder if you could already solve this issue?
