### ISSUE TITLE
VarDictJava hangs forever when BAM index is missing

### ISSUE THREAD

**Issue by clintval** [AstraZeneca-NGS/VarDictJava#187]
In the event a user has forgotten to index a BAM, the main VarDictJava process should fail-fast instead of waiting forever.

```
❯ ls
intervals.bed
ref.fa
unindexed-tumor.bam

❯ VarDictJava/build/install/VarDict/bin/VarDict \
	-N name \
	-b unindexed-tumor.bam \
	-G ref.fa \
	-p -z 1 -c 1 -S 2 -E 3 -g 4 -F 0x700 -f 0.01 -th 6 \
	intervals.bed

java.util.concurrent.ExecutionException: htsjdk.samtools.SAMException: No index is available for this BAM file.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.astrazeneca.vardict.VarDict.vardictParallel(VarDict.java:295)
	at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:265)
	at com.astrazeneca.vardict.VarDict.start(VarDict.java:74)
	at com.astrazeneca.vardict.Main.run(Main.java:138)
	at com.astrazeneca.vardict.Main.main(Main.java:25)
Caused by: htsjdk.samtools.SAMException: No index is available for this BAM file.
	at htsjdk.samtools.BAMFileReader.getIndex(BAMFileReader.java:263)
	at htsjdk.samtools.BAMFileReader.createIndexIterator(BAMFileReader.java:748)
	at htsjdk.samtools.BAMFileReader.query(BAMFileReader.java:434)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:523)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:528)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:390)
	at com.astrazeneca.vardict.VarDict$SamView.<init>(VarDict.java:1344)
	at com.astrazeneca.vardict.VarDict.parseSAM(VarDict.java:1405)
	at com.astrazeneca.vardict.VarDict.toVars(VarDict.java:2642)
	at com.astrazeneca.vardict.VarDict$VardictWorker.call(VarDict.java:5451)
	at com.astrazeneca.vardict.VarDict$VardictWorker.call(VarDict.java:5429)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

^ The above will run forever.

**Comment by PolinaBevad** [comment]
Clint, hello,
Yes, we know about this problem for exceptions in multithreading mode and it is fixed in #184. Now VarDict stops if a critical exception occurs. The next release will include this change, but it is already merged in master.

**Comment by PolinaBevad** [comment]
Clint, hello!
I will close this issue because the code is in master branch. 
As an update, just to inform you, I also created PR that will fix such problems for fasta exceptions, because they can appear before the main VarDict pipeline and will not stop by the previous implementation: https://github.com/AstraZeneca-NGS/VarDictJava/pull/214

**Comment by clintval** [comment]
Excellent! I appreciate it!
