### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException: String index out of range: 0

### ISSUE THREAD

**Issue by cbrueffer** [AstraZeneca-NGS/VarDictJava#189]
Hi,

with VarDict-Java 1.5.8 I get a reproducible exception as follows:

```
$ vardict-java -G /genomes/Hsapiens/hg38/seq/hg38.fa -c 1 -S 2 -E 3 -g 4 -b test.bam -R chr1:43894440-43894460                                                                         
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.String.charAt(String.java:658)
        at com.astrazeneca.vardict.variations.Variant.adjComplex(Variant.java:223)
        at com.astrazeneca.vardict.VarDict.vardict(VarDict.java:943)
        at com.astrazeneca.vardict.VarDict.vardictNotParallel(VarDict.java:374)
        at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:317)
        at com.astrazeneca.vardict.VarDict.start(VarDict.java:61)
        at com.astrazeneca.vardict.Main.main(Main.java:35)
```

A reduced test BAM file showing the error is available at https://lu.box.com/s/1nvqlue8ir1mgaz50d6xv9e614483udi ; the reads were aligned with HISAT 2.1.0.

**Comment by PolinaBevad** [comment]
Christian, hello!

Sorry that you have the issue. 
Thank you very much for preparing BAM file. I reproduced the error and found that it appears due to long structural variant (in this case specific deletion SV) and reference was not loaded for part of it (it is a bug). 
We will fix this soon, but if you don't need SV on this run, you can use VarDict with `--nosv` option to skip SV finding, so the error won't appear.

**Comment by cbrueffer** [comment]
Thanks for the quick diagnosis and feedback Polina! I can confirm that `--nosv` works around the issue.

**Comment by PolinaBevad** [comment]
Christian, hello!
The changes for #189, #192, #193 and #195 issues were added to master branch. 
Thank you for finding all of these! I will close these 4 issues for now and let me know if you will have any other issues or questions!
