### ISSUE TITLE
Issue while using custom reference

### ISSUE THREAD

**Issue by Subhi** [AstraZeneca-NGS/VarDictJava#190]
Hi,

I tried using a custom reference BPY.fa (which is 31646 bp). The header of my fasta file says: chrY:22973819-23005465. The bam files were aligned to this fasta file (the bam header shows @SQ    SN:chrY:22973819-23005465    LN:31646) . I have uploaded the fasta and bam too.

However when I run this command: 

`java -jar ~/my.prog/VarDictJava/build/libs/VarDict-1.6.0.jar -R “chrY:22973819-23005465” -G “/ifs/res/Y_chrom/data/artificial_ref/BPY2_ref.fa” -b “/ifs/res/Y_chrom/Mutect2_res/BPY2/TCGA-2A-A8VO/TCGA-2A-A8VO-01A-11D_chrY.bam.bwa.sorted.md.RG.bam|/ifs/res/Y_chrom/Mutect2_res/BPY2/TCGA-2A-A8VO/TCGA-2A-A8VO-10A-01D_chrY.bam.bwa.sorted.md.RG.bam"`

We get the error: 
**`Exception in thread “main” htsjdk.samtools.SAMException: Malformed query; start point 22972619 lies after end point 0
    at htsjdk.samtools.reference.IndexedFastaSequenceFile.getSubsequenceAt(IndexedFastaSequenceFile.java:215)**
    at com.astrazeneca.vardict.data.ReferenceResource.retrieveSubSeq(ReferenceResource.java:47)
    at com.astrazeneca.vardict.data.ReferenceResource.getReference(ReferenceResource.java:79)
    at com.astrazeneca.vardict.data.ReferenceResource.getReference(ReferenceResource.java:59)
    at com.astrazeneca.vardict.modes.SomaticMode.notParallel(SomaticMode.java:48)
    at com.astrazeneca.vardict.VarDictLauncher.start(VarDictLauncher.java:64)
    at com.astrazeneca.vardict.Main.main(Main.java:15)`

[Vardict_test 2.zip](https://github.com/AstraZeneca-NGS/VarDictJava/files/2894879/Vardict_test.2.zip)

**Comment by PolinaBevad** [comment]
@Subhi, hello!
Sorry that you have the issue. 
I looked at the BAM file you provided and I think it may happen because of the specific name of the chromosome that was used: it is not a `chrY`, but `chrY:22973819-23005465`. I didn't see such naming in samples before. So there are some symbols in chromosome name (`:`, `-`) that will be recognized as a part of the region and will be split, then the length of the chromosome will be calculated wrong.
Could you please rename chromosome name in BAM file to "chrY" and try again?

**Comment by PolinaBevad** [comment]
@Subhi, hello!
For several weeks there was no answer from you, so I will close the issue. But if the proposed solution does not work, please re-open this issue.
Thank you!
