### ISSUE TITLE
StringIndexOutOfBoundsException when disabling realignment

### ISSUE THREAD

**Issue by cbrueffer** [AstraZeneca-NGS/VarDictJava#193]
Hi,

I can reproduce the following exception with VarDict-Java 1.5.8 when disabling realignment using `-t 0`.

```
vardict-java -G /genomes/Hsapiens/hg38-mut-cb/seq/hg38-mut-cb.fa -c 1 -S 2 -E 3 -g 4 -b test-norealign-stringindex-oob.bam --nosv -k 0 -R chr22:20566544-20566545
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -2
        at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
        at java.base/java.lang.String.charAt(String.java:693)
        at com.astrazeneca.vardict.modules.SAMFileParser.parseSAM(SAMFileParser.java:690)
        at com.astrazeneca.vardict.modules.ToVarsBuilder.toVars(ToVarsBuilder.java:69)
        at com.astrazeneca.vardict.VarDict.vardictNotParallel(VarDict.java:372)
        at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:317)
        at com.astrazeneca.vardict.VarDict.start(VarDict.java:61)
        at com.astrazeneca.vardict.Main.main(Main.java:35)
```

Enabling realignment using `-t 1` works around the problem. The reads were aligned with HISAT 2.1.0.

A minimal BAM file exhibiting the problem: https://lu.box.com/s/df184jkirjkrchoc2viecefbabqjcvu9

**Comment by PolinaBevad** [comment]
The fix is merged.
