### ISSUE TITLE
Realignment problem: java.lang.NumberFormatException: For input string: "∞"

### ISSUE THREAD

**Issue by cbrueffer** [AstraZeneca-NGS/VarDictJava#195]
Hi,

here's another problem related to realignment in VarDict-Java 1.5.8; it can be avoided by setting `-k 0`:

```
vardict-java -G /genomes/Hsapiens/hg38/seq/hg38.fa -c 1 -S 2 -E 3 -g 4 -b test-invalid-char.bam --nosv -R chr9:107331083-107331084
Exception in thread "main" java.lang.NumberFormatException: For input string: "∞"
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
        at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.base/java.lang.Double.parseDouble(Double.java:543)
        at com.astrazeneca.vardict.Utils.roundHalfEven(Utils.java:102)
        at com.astrazeneca.vardict.modules.ToVarsBuilder.toVars(ToVarsBuilder.java:620)
        at com.astrazeneca.vardict.VarDict.vardictNotParallel(VarDict.java:372)
        at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:317)
        at com.astrazeneca.vardict.VarDict.start(VarDict.java:61)
        at com.astrazeneca.vardict.Main.main(Main.java:35)
```

BAM file to reproduce: https://lu.box.com/s/6ce9gzv1zzkucabhoi4750ghqkl91j91

The last record in the file is the one triggering the problem.

**Comment by PolinaBevad** [comment]
Christian, hello,
The current issue also occurs when there are three indels in CIGAR but in a slightly different case (the final cigar has `0D` which is not a good situation). 

Here is the cumulative fix for 189, 192 and 195 issues, it will be great if you could test it on your samples to be sure we avoid all type of errors with these three indels CIGARs and SV reference: https://drive.google.com/open?id=15PFpkBe52klm5j3WhYY1ndSu87t-pEyw 
Because it also fix 189, you can try VarDictJava without `--nosv` option. 

One issue left (193) requires a bit more analysis.
Thank you for preparing good test examples and problem descriptions!

**Comment by cbrueffer** [comment]
This version works with all samples I've tested it on, thanks!

I've noticed high memory consumption (needed -Xmx32G with 8 threads for some samples), but I think the last version I used on a larger number of samples didn't do SV calling, so I suppose that's expected.

**Comment by PolinaBevad** [comment]
Great, thank you for testing this!
Yes, SV analysis will take more memory, because during the calling it can expand regions to find very long SVs. We usually test our samples in the configuration with -Xmx8G, but if you have long regions in BED file and they will also be extended in SV calling for specific samples, then the memory consumption can increase significantly.

**Comment by PolinaBevad** [comment]
The fix is merged.
