### ISSUE TITLE
error with mutation calling

### ISSUE THREAD

**Issue by elainebblythe** [AstraZeneca-NGS/VarDictJava#201]
my code is :
$vardict/VarDict \
                -G $ref \
                -N AYG9V-S1 \
                -f 0.01 \
                -b AYG9V-S1.consensus.merged.filter.clip.bam \
                -z -c 1 -S 2 -E 3 -g 4 -th 4 \
                SampleID_probes.bed >test.vcf
 
and the I meet this error

java.util.concurrent.ExecutionException: java.lang.NumberFormatException: null
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.astrazeneca.vardict.VarDict.vardictParallel(VarDict.java:354)
        at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:319)
        at com.astrazeneca.vardict.VarDict.start(VarDict.java:76)
        at com.astrazeneca.vardict.Main.main(Main.java:35)
Caused by: java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Integer.java:542)
        at java.lang.Integer.parseInt(Integer.java:615)
        at com.astrazeneca.vardict.Utils.toInt(Utils.java:91)
        at com.astrazeneca.vardict.modules.StructuralVariantsProcessor.prepareSVStructuresForAnalysis(StructuralVariantsProcessor.java:87)
        at com.astrazeneca.vardict.modules.SAMFileParser.parseSAM(SAMFileParser.java:312)
        at com.astrazeneca.vardict.modules.ToVarsBuilder.toVars(ToVarsBuilder.java:69)
        at com.astrazeneca.vardict.VarDict$VardictWorker.call(VarDict.java:1044)
        at com.astrazeneca.vardict.VarDict$VardictWorker.call(VarDict.java:1019)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Is there a problem with my code or a problem with my java?

**Comment by PolinaBevad** [comment]
@elainebblyth, hello!
Sorry that you have a problem with VarDict!

This bug occurs in VarDictJava 1.5.8 version for structural variants analysis and it has been fixed, but the fix is not yet included in the new release (it will be in future version 1.6.0). 
If you clone and build VarDictJava as described here: https://github.com/AstraZeneca-NGS/VarDictJava#getting-started, then you can run VarDict with all the fixes that we have at the moment.
Could you try this? Feel free to ask any questions.

**Comment by elainebblythe** [comment]
ok,I will try it.
thank for your reply.



elaineylq@163.com
 
From: Polina Bevad
Date: 2019-03-13 17:48
To: AstraZeneca-NGS/VarDictJava
CC: elainebblythe; Author
Subject: Re: [AstraZeneca-NGS/VarDictJava] error with mutation calling (#201)
@elainebblyth, hello!
Sorry that you have a problem with VarDict!
This bug occurs in VarDictJava 1.5.8 version for structural variants analysis and it has been fixed, but the fix is not yet included in the new release (it will be in future version 1.6.0).
If you clone and build VarDictJava as described here: https://github.com/AstraZeneca-NGS/VarDictJava#getting-started, then you can run VarDict with all the fixes that we have at the moment.
Could you try this? Feel free to ask any questions.

**Comment by PolinaBevad** [comment]
@elainebblythe, hello!
I will close the issue because the problem was solved before and you can use the new version from master branch. Please, let me know if you will have any other questions.

**Comment by elainebblythe** [comment]
ok,thanks



elaineylq@163.com
 
From: Polina Bevad
Date: 2019-04-18 21:01
To: AstraZeneca-NGS/VarDictJava
CC: elainebblythe; Mention
Subject: Re: [AstraZeneca-NGS/VarDictJava] error with mutation calling (#201)
@elainebblythe, hello!
I will close the issue because the problem was solved before and you can use the new version from master branch. Please, let me know if you will have any other questions.
