### ISSUE TITLE
NoClassDefFoundError: CountingOutputStream

### ISSUE THREAD

**Issue by gevro** [AstraZeneca-NGS/VarDictJava#205]
Hi, I'm getting the below error (first time trying to run VarDict).
I can't figure out what is wrong.
Any suggestions?

$ VarDict -N NA12877 -b NA12877.cram -G Homo_sapiens_assembly38.fasta hg38-gatk.1mb.windows 
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/CountingOutputStream
	at htsjdk.samtools.cram.build.CramIO.readSAMFileHeader(CramIO.java:276)
	at htsjdk.samtools.cram.build.CramIO.readCramHeader(CramIO.java:213)
	at htsjdk.samtools.cram.build.CramContainerIterator.<init>(CramContainerIterator.java:23)
	at htsjdk.samtools.CRAMIterator.<init>(CRAMIterator.java:85)
	at htsjdk.samtools.CRAMFileReader.initWithStreams(CRAMFileReader.java:226)
	at htsjdk.samtools.CRAMFileReader.<init>(CRAMFileReader.java:219)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:347)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:169)
	at com.astrazeneca.vardict.VarDictLauncher.readChr(VarDictLauncher.java:183)
	at com.astrazeneca.vardict.VarDictLauncher.initResources(VarDictLauncher.java:76)
	at com.astrazeneca.vardict.VarDictLauncher.start(VarDictLauncher.java:48)
	at com.astrazeneca.vardict.Main.main(Main.java:15)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.utils.CountingOutputStream
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more

**Comment by gevro** [comment]
Looks like I overcame this error by changing the line in build.gradle to get the latest version of htsjdk:
CHANGED TO: compile('com.github.samtools:htsjdk:2.19.0') { 

But now I'm getting another obscure error:
INFO	2019-03-24 23:22:04	Defaults	Found file for property samjdk.reference_fasta: Homo_sapiens_assembly38.fasta 
INFO	2019-03-24 23:22:04	ReferenceSource	Default reference file Homo_sapiens_assembly38.fasta exists, so going to use that.
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/compress/compressors/xz/XZCompressorInputStream
	at htsjdk.samtools.cram.structure.block.Block.getUncompressedContent(Block.java:203)
	at htsjdk.samtools.cram.build.CramIO.readSAMFileHeader(CramIO.java:302)
	at htsjdk.samtools.cram.build.CramIO.readCramHeader(CramIO.java:218)
	at htsjdk.samtools.cram.build.CramContainerIterator.<init>(CramContainerIterator.java:24)
	at htsjdk.samtools.CRAMIterator.<init>(CRAMIterator.java:86)
	at htsjdk.samtools.CRAMFileReader.initWithStreams(CRAMFileReader.java:226)
	at htsjdk.samtools.CRAMFileReader.<init>(CRAMFileReader.java:219)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:422)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:208)
	at com.astrazeneca.vardict.VarDictLauncher.readChr(VarDictLauncher.java:183)
	at com.astrazeneca.vardict.VarDictLauncher.initResources(VarDictLauncher.java:76)
	at com.astrazeneca.vardict.VarDictLauncher.start(VarDictLauncher.java:48)
	at com.astrazeneca.vardict.Main.main(Main.java:15)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.compressors.xz.XZCompressorInputStream
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more

**Comment by PolinaBevad** [comment]
@gevro, hello!
Sorry that you have the issue!

Can you please try to delete line `transitive = false` for htsjdk in `build.gradle` and try to run it again?
If it doesn't help, can you send a small part of CRAM file which causes the error to polina_bevad@epam.com? I will check it.

**Comment by gevro** [comment]
Thanks, that fixed it!
