### ISSUE TITLE
NumberFormatException error

### ISSUE THREAD

**Issue by gevro** [AstraZeneca-NGS/VarDictJava#206]
Hi,
I'm getting the below error when running this:
VarDict -U -N NA12877 -O 10 -b NA12877.cram -G Homo_sapiens_assembly38.fasta hg38-gatk.1mb.windows

Any idea what is wrong?

*Error:
Exception in thread "main" java.lang.NumberFormatException: For input string: "chr1_10001_207666_1"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.astrazeneca.vardict.Utils.toInt(Utils.java:91)
	at com.astrazeneca.vardict.RegionBuilder.buildRegions(RegionBuilder.java:73)
	at com.astrazeneca.vardict.VarDictLauncher.initResources(VarDictLauncher.java:98)
	at com.astrazeneca.vardict.VarDictLauncher.start(VarDictLauncher.java:48)
	at com.astrazeneca.vardict.Main.main(Main.java:15)

*Input BED file:
chr1	10001	207666	chr1_10001_207666_1
chr1	257667	297968	chr1_257667_297968_1
chr1	347969	535988	chr1_347969_535988_1
chr1	585989	1585989	chr1_585989_2702781_1
chr1	1585689	2585689	chr1_585989_2702781_2
chr1	2585389	2702781	chr1_585989_2702781_3
chr1	2746291	3746291	chr1_2746291_12954384_1
chr1	3745991	4745991	chr1_2746291_12954384_2
chr1	4745691	5745691	chr1_2746291_12954384_3

**Comment by PolinaBevad** [comment]
@gevro, hello!
Could you please attach the part of BED as a file? It is not very clear that you don't have extra spaces or tabs in the file when I look at the issue text. 
The error means that you have the error in the second column (when start of region is parsing). 
The file must be tab delimited with columns: chr, start, end, gene.

**Comment by gevro** [comment]
Sure, attached.
[hg38-gatk.1mb.windows.head30.txt](https://github.com/AstraZeneca-NGS/VarDictJava/files/3008542/hg38-gatk.1mb.windows.head30.txt)

**Comment by PolinaBevad** [comment]
Okay, thanks. I think I found out the reason: VarDict tries to set another BED format (with 12 columns). Please, add to your command line attributes `-c 1 -S 2 -E 3 -g 4` to manually set the numbers of columns in BED file and try it again.

**Comment by gevro** [comment]
Thanks works!
