### ISSUE TITLE
VarDict Java expected run time and memory

### ISSUE THREAD

**Issue by thkitapci** [AstraZeneca-NGS/VarDictJava#216]
Hi,
Can you give an estimated run time for a given BAM file size for VarDictJava ? I understand this would be highly dependent on the system being run. I have a BAM file of 5GB in size. Running the command 

`AF_THR="0.01" # minimum allele frequency
<path_to_vardict_folder>/build/install/VarDict/bin/VarDict -G /path/to/hg19.fa -f $AF_THR -N sample_name -b /path/to/my.bam -z -c 1 -S 2 -E 3 -g 4 /path/to/my.bed | VarDict/teststrandbias.R | VarDict/var2vcf_valid.pl -N sample_name -E -f $AF_THR`

takes over 24 hours using 1 CPU with 16GB RAM. Is this within the expected range for runtime ? Java implementation was supposed to be 10 times faster than the perl implementation so I was expecting faster than 24 hours for a 5GB BAM file. 

Thanks
Best Regards
T. Hamdi Kitapci

**Comment by PolinaBevad** [comment]
Hi Hamdi,
Time is completely dependent on the specifics of the data. If you have not a very big amount of regions in BED, but with high coverage, it will take more time then a big amount of regions with smaller coverage. For example, in one of my runs, 30Gb not high coverage BAM is processed on 8 cores and 16 Gb RAM for 1 h 40 minutes. But another high coverage BAM 1,6 Gb is processed on 8 cores for 20 minutes. It happens because VarDict uses local realignment and SV calling as one of the steps, so high coverage regions or regions with bad mapping can take more time to process. 
Does your BED file contains some long regions (i.e. 1 million bases and more) or it was created from GTF?
Anyway, it is better to use multithread mode because it will decrease the time of processing significantly: each region will be processed on a separate core (i.e. with 8 cores you will have 7 regions processed in one time and one main thread).

**Comment by PolinaBevad** [comment]
Hi Hamdi!
Can I close this issue or you have any other questions about VarDict performance?

**Comment by thkitapci** [comment]
Hi @PolinaBevad ,
One more question regarding the memory. Does the memory requirement linearly scale with the size of the bam file ? 

Thanks
Best Regards
Hamdi

**Comment by PolinaBevad** [comment]
Hi Hamdi,

Well, not indeed. VarDictJava works on each region separately and it will keep in memory the reference from the region (the size will be based on regions in BED file you provide) and some intermediate structures for variants, but it doesn't keep in memory reads from BAM file. VarDict parses each read from the region and saves only the information about these structures: ref allele and varallele with their counts, quality data and so on. 

So if you have high coverage in BAM (i.e. it will be much bigger then with small coverage), it does not take more memory then BAM file with the same regions but smaller coverage, because it will simply increase or decrease counts in already existing structures. Instead of this time of processing can increase. 

Based on all this, it is better to have not very big regions in BED file (for WGS about 10-100 kbp or exome regions), then the stored reference sequence will not very big, and memory will release frequently.

**Comment by thkitapci** [comment]
Hi @PolinaBevad, 
I am running my analysis on the entire transcriptome using the command

VarDict -th 8 -G $reference_fasta -f $AF_THR -N $sample_name -b "$bam_file_exp1|$bam_file_control" -c 1 -S 2 -E 3 -g 4 $bed_file 2>$sample_name.vardictError >$sample_name.vardictOut

with the following Bed file: https://drive.google.com/file/d/1i3aV-MlIiIg8Uw3CLpsnd2iyV9_ESHdw/view?usp=sharing

and the following Fasta file: https://drive.google.com/file/d/1R2dAi9kQQsgATQr0gaB857Zha_0wC4IK/view?usp=sharing

Here is the full installation directory for VarDictJava: https://drive.google.com/drive/folders/1f8wXE-LMtuEvANc74-dPfjPqS4cdj4uX?usp=sharing

The executable used in the above command is VarDictJava/build/install/VarDict/bin/VarDict

I can also share my Bam files if needed. 

I am getting the following error

Critical exception occurs on region: 10:63430097-65002965, program will be stopped.
Critical exception occurs on region: 10:63430097-65003667, program will be stopped.
java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: Java heap space
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1975)
        at com.astrazeneca.vardict.modes.AbstractMode.pipeline(AbstractMode.java:51)
        at com.astrazeneca.vardict.modes.SomaticMode.processBothBamsInPipeline(SomaticMode.java:122)
        at com.astrazeneca.vardict.modes.SomaticMode.access$000(SomaticMode.java:31)
        at com.astrazeneca.vardict.modes.SomaticMode$SomdictWorker.call(SomaticMode.java:96)
        at com.astrazeneca.vardict.modes.SomaticMode$SomdictWorker.call(SomaticMode.java:79)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.lang.StringBuffer.toString(StringBuffer.java:673)
        at java.text.DecimalFormat.applyPattern(DecimalFormat.java:3441)
        at java.text.DecimalFormat.<init>(DecimalFormat.java:436)
        at com.astrazeneca.vardict.Utils.roundHalfEven(Utils.java:102)
        at com.astrazeneca.vardict.modules.ToVarsBuilder.createVariant(ToVarsBuilder.java:415)
        at com.astrazeneca.vardict.modules.ToVarsBuilder.process(ToVarsBuilder.java:120)
        at com.astrazeneca.vardict.modes.AbstractMode$$Lambda$26/171723046.apply(Unknown Source)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        ... 11 more
java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: Java heap space
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1975)
        at com.astrazeneca.vardict.modes.AbstractMode.pipeline(AbstractMode.java:51)
        at com.astrazeneca.vardict.modes.SomaticMode.processBothBamsInPipeline(SomaticMode.java:122)
        at com.astrazeneca.vardict.modes.SomaticMode.access$000(SomaticMode.java:31)
        at com.astrazeneca.vardict.modes.SomaticMode$SomdictWorker.call(SomaticMode.java:96)
        at com.astrazeneca.vardict.modes.SomaticMode$SomdictWorker.call(SomaticMode.java:79)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.lang.StringBuffer.toString(StringBuffer.java:673)
        at java.text.DecimalFormat.applyPattern(DecimalFormat.java:3416)
        at java.text.DecimalFormat.<init>(DecimalFormat.java:436)
        at com.astrazeneca.vardict.Utils.roundHalfEven(Utils.java:102)
        at com.astrazeneca.vardict.modules.ToVarsBuilder.createVariant(ToVarsBuilder.java:391)
        at com.astrazeneca.vardict.modules.ToVarsBuilder.process(ToVarsBuilder.java:120)
        at com.astrazeneca.vardict.modes.AbstractMode$$Lambda$26/171723046.apply(Unknown Source)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        ... 11 more

I run this job first with 16GB ram then 32 GB ram and I got the same error. Then I move to a very large memory node with has 1 TB ram and I got this error again (the error message I posted is from the last run with 1 TB of RAM) I think it is impossible that VarDict is using all the ram and running out of memory. Something else must be wrong here can you please help me debug the problem ? Let me know if you need any additional information to debug this.

Best Regards
Hamdi

**Comment by PolinaBevad** [comment]
Hamdi, hello!
Sorry that you have this error. 

The region were VarDict stops is big (about 1,5 Mbp), but it must be processed if you will increase Java heap space. If you simply move run of Java program on the node with bigger amount of memory, nothing will changed, because you have to increase heap space manually. You can find the description of the solution here: https://github.com/AstraZeneca-NGS/VarDictJava/wiki/Error-java.lang.OutOfMemoryError:-GC-overhead-limit-exceeded

Could you please try to change heap space up to 16 Gb, for example? If you will use smaller regions in the BED file, the problem also will not occur. If it will repeat, could you   provide the part of BAM file with the region that is mentioned in the error?

**Comment by thkitapci** [comment]
Hi @PolinaBevad,
Thanks for the reply. I see that in my VarDict script the default values are set to 

# Add default JVM options here. You can also use JAVA_OPTS and VAR_DICT_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xms768m" "-Xmx8g"'

I understand that I was allowing maximum of 8gb of RAM and that was why I got these out of memory error. 

Given the size of my BED file is there a way to estimate the memory requirement or do I have to do trials to see what memory I need ?

Thanks
Best Regards
Hamdi

**Comment by PolinaBevad** [comment]
Hi Hamdi,

Because Java memory is not simple to be predicted (it has different types of garbage collectors and many auto-tuned properties), it is not very accurate, but I often estimate needed memory by about 1Mb for 1 bp of region (here are included possible intermediate structures for variations, reference and softclips). Also you have to take account of amount of threads that you run, because memory will be used by all of them and will be split between threads. So in your case I think 16GB must be enough in run on 8 threads if you have regions about 1,5 Mbp. If you run 1 thread, then 8 Gb also would be enough, because only one region will be held in memory in once. 
If there will be a lot of softclips in your data (quite specific situation) it can take more memory while realigning, but I provided the typical configuration. 
Let me know if you will get any errors after increasing the heap space!

**Comment by thkitapci** [comment]
Hi @PolinaBevad,
I run vardict again by setting the environmental variable

`VAR_DICT_OPTS='"-Xms32g" "-Xmx900g"'
VarDict -th 8 -G $reference_fasta -f $AF_THR -N $sample_name -b "$bam_file_exp1|$bam_file_control" -c 1 -S 2 -E 3 -g 4 $bed_file 2>$sample_name.vardictError.FirstStep >$sample_name.vardictOut.FirstStep
`

This is runnning on a machine with 1TB of RAM based on the environmental variable the memory should start at 32g and extend all the way up to 900g

Am I making a mistake setting the environmental variable ? Is there a way to check the memory assigned to java while running vardict ? I looked at the output file and it failed at the same place as my previous run so either I am unable to increase the memory or there is something else going on the error message I got is

`Critical exception occurs on region: 10:63457509-65003667, program will be stopped.
java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1975)
        at com.astrazeneca.vardict.modes.AbstractMode.pipeline(AbstractMode.java:51)
        at com.astrazeneca.vardict.modes.SomaticMode.processBothBamsInPipeline(SomaticMode.java:122)
        at com.astrazeneca.vardict.modes.SomaticMode.access$000(SomaticMode.java:31)
        at com.astrazeneca.vardict.modes.SomaticMode$SomdictWorker.call(SomaticMode.java:96)
        at com.astrazeneca.vardict.modes.SomaticMode$SomdictWorker.call(SomaticMode.java:79)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at sun.util.locale.provider.DecimalFormatSymbolsProviderImpl.getInstance(DecimalFormatSymbolsProviderImpl.java:85)
        at java.text.DecimalFormatSymbols.getInstance(DecimalFormatSymbols.java:180)
        at java.text.DecimalFormat.<init>(DecimalFormat.java:435)
        at com.astrazeneca.vardict.Utils.roundHalfEven(Utils.java:102)
        at com.astrazeneca.vardict.modules.ToVarsBuilder.createVariant(ToVarsBuilder.java:391)
        at com.astrazeneca.vardict.modules.ToVarsBuilder.process(ToVarsBuilder.java:120)
        at com.astrazeneca.vardict.modes.AbstractMode$$Lambda$27/314629764.apply(Unknown Source)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        ... 11 more
`

Thanks for your help
Hamdi

**Comment by PolinaBevad** [comment]
Hi Hamdi, 
Sorry I forgot to say that it must be not a simple variable, but enviromental variable, so you have to set it like this: 
`export VAR_DICT_OPTS='"-Xms32g" "-Xmx900g"'`
instead of this
`VAR_DICT_OPTS='"-Xms32g" "-Xmx900g"'`
In second case it can be accessed only in scope of the script that you run and not other programs (gradle, JVM, etc). Please, try to use it with `export` command.
You can also check that variable now is available in enviroment by starting this before VarDict:
`printenv | grep OPTS`
If everything is ok, you will get the line VAR_DICT_OPTS='"-Xms32g" "-Xmx900g"'`

**Comment by thkitapci** [comment]
Hi @PolinaBevad,
Thanks for the clarification. After setting the variable as an environmental variable with "export" it worked fine. 

Thanks!
Hamdi

**Comment by PolinaBevad** [comment]
Hamdi, hello!
Great, thank you for notifying! 
I will close the issue, please feel free to create new issue if you will have any other questions.
