### ISSUE TITLE
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0

### ISSUE THREAD

**Issue by mjafin** [AstraZeneca-NGS/VarDictJava#22]
Hi there,
I'm calling variants in hg38 and am getting this error:
```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.String.charAt(String.java:658)
        at com.astrazeneca.vardict.VarDict.varType(VarDict.java:5905)
        at com.astrazeneca.vardict.VarDict.vardict(VarDict.java:966)
        at com.astrazeneca.vardict.VarDict.vardictNotParallel(VarDict.java:305)
        at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:257)
        at com.astrazeneca.vardict.VarDict.start(VarDict.java:68)
        at com.astrazeneca.vardict.Main.run(Main.java:134)
        at com.astrazeneca.vardict.Main.main(Main.java:25)
' returned non-zero exit status 1
```
This is in the chrUn_GL000216v2 contig that is fairly short (0-176608). I can provide you the data via Box again when you have time to pick this up.

Thanks,
Miika

**Comment by chapmanb** [comment]
Miika;
It sounds like this might be the same as the issue in this PR: https://github.com/AstraZeneca-NGS/VarDictJava/pull/19 It's a small fix but hadn't gotten pulled into main and a release yet, as far as I know.

**Comment by mjafin** [comment]
Brad, thanks, well spotted! I'll flag these up with EPAM and will follow up properly

**Comment by mjafin** [comment]
This issue seems to have been solved now, thanks! I'll reopen if I come across it again.
