### ISSUE TITLE
Exceptions: index out of bound error related to hard clipping

### ISSUE THREAD

**Issue by gpratt** [AstraZeneca-NGS/VarDictJava#253]
Hello,

I think I've discovered bug related to, but slightly different from #243.

It appears that when a read is hard-clipped and the 5' end of the read starts with an insertion `StringIndexOutOfBoundsException` error occurs.

To show this effect I've included two minimally reproducing examples with a single read.  

Data Set: [reproducing_data.tar.gz](https://github.com/AstraZeneca-NGS/VarDictJava/files/3504010/reproducing_data.tar.gz)

Contents:

```
❯ tree reproducing_data
reproducing_data
├── example_1
│   ├── example_1.bam
│   ├── example_1.bam.bai
│   ├── example_1.bed
│   ├── example_1.fa
│   └── example_1.fa.fai
└── example_2
    ├── example_2.bam
    ├── example_2.bam.bai
    ├── example_2.bed
    ├── example_2.fa
    └── example_2.fa.fai
```

When VarDictJava is run on `example_1`:

```
VarDictJava/build/install/VarDict/bin/VarDict \
    -N test \
    -b example_1.bam \
    -G example_1.fa \
    -p \
    -z 1 \
    -c 1 \
    -S 2 \
    -E 3 \
    -g 4 \
    -f 0.0 \
    -r 1 \
    example_1.bed
```

 The following exception is thrown:
 
 ```
There was Exception while processing record on read_1 on region test:6675-6824. The processing will be continued from the next record.
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.charAt(String.java:658)
	at com.astrazeneca.vardict.modules.CigarParser.processDeletion(CigarParser.java:657)
	at com.astrazeneca.vardict.modules.CigarParser.parseCigar(CigarParser.java:354)
	at com.astrazeneca.vardict.modules.CigarParser.process(CigarParser.java:89)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983)
	at com.astrazeneca.vardict.modes.AbstractMode.pipeline(AbstractMode.java:48)
	at com.astrazeneca.vardict.modes.SimpleMode.processBamInPipeline(SimpleMode.java:103)
	at com.astrazeneca.vardict.modes.SimpleMode.notParallel(SimpleMode.java:45)
	at com.astrazeneca.vardict.VarDictLauncher.start(VarDictLauncher.java:65)
	at com.astrazeneca.vardict.Main.main(Main.java:15)

```

A similar error occurs is with `example_2`:

```
VarDictJava/build/install/VarDict/bin/VarDict \
    -N test \
    -b example_2.bam \
    -G example_2.fa \
    -p \
    -z 1 \
    -c 1 \
    -S 2 \
    -E 3 \
    -g 4 \
    -f 0.0 \
    -r 1 \
    example_2.bed

There was Exception while processing record on read_1 on region test:6435-6564. The processing will be continued from the next record.
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.charAt(String.java:658)
	at com.astrazeneca.vardict.modules.CigarParser.processDeletion(CigarParser.java:657)
	at com.astrazeneca.vardict.modules.CigarParser.parseCigar(CigarParser.java:354)
	at com.astrazeneca.vardict.modules.CigarParser.process(CigarParser.java:89)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983)
	at com.astrazeneca.vardict.modes.AbstractMode.pipeline(AbstractMode.java:48)
	at com.astrazeneca.vardict.modes.SimpleMode.processBamInPipeline(SimpleMode.java:103)
	at com.astrazeneca.vardict.modes.SimpleMode.notParallel(SimpleMode.java:45)
	at com.astrazeneca.vardict.VarDictLauncher.start(VarDictLauncher.java:65)
	at com.astrazeneca.vardict.Main.main(Main.java:15)
```

I think this minimally has to do with hard clipping, removing the hard clipping CIGAR string fixes the exception, however when I was trying to edit the read structures to make an even simpler example I inadvertently fixed the exception I was trying to reproduce, so there might be something more complicated going on.  

Thanks again for any thoughts or help!

**Comment by PolinaBevad** [comment]
Hi, Gabriel,

Thank you for finding this!
Yes, you are right about hard clips, an error appears because of them. We don't need to modify CIGAR in the case when 2 close indels appear right after hard-clip, so I added this exclusion to the algorithm. 

I've prepared a fix for this: https://github.com/AstraZeneca-NGS/VarDictJava/pull/254 so you can try it on your samples.

Thank you for providing good test cases! I added them to our integration testing.

**Comment by gpratt** [comment]
Thanks so much! Thats a blazingly fast fix time.  Looks like it works!

**Comment by PolinaBevad** [comment]
Gabriel, hello!
We merged this fix in master, so you can build and use it. I'll close this issue, but feel free to open it if needed!
