### ISSUE TITLE
"Critical exception occurs on region: [...] java.lang.ArithmeticException: / by zero"

### ISSUE THREAD

**Issue by LukeGoodsell** [AstraZeneca-NGS/VarDictJava#272]
Hi,

I've been very happily running tumour-normal somatic variant calling with VarDictJava for some time, but have just encountered a situation where VarDict has died with this error message:

```
Critical exception occurs on region: chr19:291456-291774, program will be stopped.
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.lang.ArithmeticException: / by zero
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983)
        at com.astrazeneca.vardict.modes.AbstractMode.pipeline(AbstractMode.java:49)
        at com.astrazeneca.vardict.postprocessmodules.SomaticPostProcessModule.combineAnalysis(SomaticPostProcessModule.java:391)
        at com.astrazeneca.vardict.postprocessmodules.SomaticPostProcessModule.printVariationsFromFirstSample(SomaticPostProcessModule.java:186)
        at com.astrazeneca.vardict.postprocessmodules.SomaticPostProcessModule.callingForBothSamples(SomaticPostProcessModule.java:133)
        at com.astrazeneca.vardict.postprocessmodules.SomaticPostProcessModule.accept(SomaticPostProcessModule.java:87)
        at com.astrazeneca.vardict.postprocessmodules.SomaticPostProcessModule.accept(SomaticPostProcessModule.java:28)
        at java.util.concurrent.CompletableFuture.biAccept(CompletableFuture.java:1176)
        at java.util.concurrent.CompletableFuture.biAcceptStage(CompletableFuture.java:1192)
        at java.util.concurrent.CompletableFuture.thenAcceptBoth(CompletableFuture.java:2043)
        at com.astrazeneca.vardict.modes.SomaticMode.processBothBamsInPipeline(SomaticMode.java:125)
        at com.astrazeneca.vardict.modes.SomaticMode.access$000(SomaticMode.java:31)
        at com.astrazeneca.vardict.modes.SomaticMode$SomdictWorker.call(SomaticMode.java:96)
        at com.astrazeneca.vardict.modes.SomaticMode$SomdictWorker.call(SomaticMode.java:79)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.ArithmeticException: / by zero
        at com.astrazeneca.vardict.Utils.printExceptionAndContinue(Utils.java:270)
        at com.astrazeneca.vardict.modules.VariationRealigner.realignlgins(VariationRealigner.java:1757)
        at com.astrazeneca.vardict.modules.VariationRealigner.realignIndels(VariationRealigner.java:399)
        at com.astrazeneca.vardict.modules.VariationRealigner.process(VariationRealigner.java:88)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        ... 19 more
Caused by: java.lang.ArithmeticException: / by zero
        at com.astrazeneca.vardict.modules.StructuralVariantsProcessor.markDUPSV(StructuralVariantsProcessor.java:1691)
        at com.astrazeneca.vardict.modules.VariationRealigner.realignlgins(VariationRealigner.java:1674)
        ... 22 more
```

I have had this error with versions v1.7.0-g90d8ee1 and v1.5.8-gf70d926, but not with v1.5.1-g514215a. Disabling structural variant calling (with `-U`), allows the newer versions to work, so as the stack trace suggests this is isolated to structural variant calling.

I'm calling VarDict with a command such as this (sample and file names changed):

```
export VAR_DICT_OPTS="-Xms768m -Xmx30g"
VarDict \
        -X 3 \
        -G ucsc.hg19-GATKBundle.fa \
        -f 0.0001 \
        -N TUMOUR \
        -b 'tumour.bam|normal.bam' \
        -th 8 \
        -c 1 -S 2 -E 3 \
        intervals.bed \
    > tumour.vardictjava.var \
    2> tumour.vardictjava.stderr.txt
```

Is this a known issue? Can you suggest anything I can do to diagnose this issue?

**Comment by LukeGoodsell** [comment]
In case they are helpful, here is a zip file containing a minimal pair of BAM files with accompanying indices and interval BED file: [vardict_example.zip](https://github.com/AstraZeneca-NGS/VarDictJava/files/3778227/vardict_example.zip).

The error can be reproduced with this command:

```
export VAR_DICT_OPTS="-Xms768m -Xmx30g"
VarDict \
        -X 3 \
        -G /data/genome/ucsc.hg19-GATKBundle/fasta/uncompressed/ucsc.hg19-GATKBundle.fa \
        -f 0.0001 \
        -N PATIENT_TUMOUR \
        -b 'PATIENT_TUMOUR.bam|PATIENT_NORMAL.bam' \
        -th 8 \
        -c 1 -S 2 -E 3 \
        interval.bed \
    > vardictjava_calls.var
```

**Comment by PolinaBevad** [comment]
Hi Luke,
Sorry, that you have the issue! Thanks for providing a test case, this is very useful for debugging.

I found the reason, yes it appears in structural variant analysis for some possible SV clusters. 
I've prepared a fix here: https://github.com/AstraZeneca-NGS/VarDictJava  This fix will be included in the next VarDict release.
You can use the branch from PR to run your samples at the moment (you will have to build it manually https://github.com/AstraZeneca-NGS/VarDictJava#compiling).

**Comment by LukeGoodsell** [comment]
Thanks for the quick turn-around, Polina!
