### ISSUE TITLE
Ignoring SAM validation error

### ISSUE THREAD

**Issue by inti** [AstraZeneca-NGS/VarDictJava#28]
Hello,
I am getting this error when running verdict-java on alignments from RNA-seq. The alignments were generated by the following command line
```
@PG	ID:GSNAP.1	PN:gsnap	CL:gsnap -D /home/shared/ref_genome/Poplar/ -d poplarv3_gsnap --nthreads=16 -s gsnap_db/stringtie_cuffmerge/gtf_splicesite_file.iit -V gsnap_db/hisat_freebayes/snp/local_vcf_db_snp.iit --use-sarray=0 -B 5 -a paired -N 1 -m 4 -M 1 -i 2 -w 500000 -E 4 -n 100 --pairmax-rna=200000 --gmap-mode=pairsearch -A sam -O --read-group-id=SRR073112 --read-group-name=BELA --gunzip fastq//SRR073112_1.fastq.gz fastq//SRR073112_2.fastq.gz	VN:2015-12-31
```
The error message is 
```
Ignoring SAM validation error: ERROR: Record 6874, Read name SRR073112.8947314, Mate Alignment start (25847531) must be <= reference sequence length (25263035) on reference Chr02
java.util.concurrent.ExecutionException: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.astrazeneca.vardict.VarDict.vardictParallel(VarDict.java:289)
	at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:259)
	at com.astrazeneca.vardict.VarDict.start(VarDict.java:68)
	at com.astrazeneca.vardict.Main.run(Main.java:134)
	at com.astrazeneca.vardict.Main.main(Main.java:25)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.charAt(Unknown Source)
	at com.astrazeneca.vardict.VarDict.isHasAndNotEquals(VarDict.java:4068)
	at com.astrazeneca.vardict.VarDict.modifyCigar(VarDict.java:6179)
	at com.astrazeneca.vardict.VarDict.parseSAM(VarDict.java:1534)
	at com.astrazeneca.vardict.VarDict.toVars(VarDict.java:2538)
	at com.astrazeneca.vardict.VarDict$VardictWorker.call(VarDict.java:5374)
	at com.astrazeneca.vardict.VarDict$VardictWorker.call(VarDict.java:5352)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```
And the information on the bam file for that read is the following
```
SRR073112.8947314	435	Chr02	75272	0	50M	=	25847531	965	ACGTGAACGTCTTTATGAGAAGATGGGAATTGGCAGCAGTTATCTTTTTA	II@4:I8IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	RG:Z:SRR073112	MD:Z:7A1A40	NH:i:2	HI:i:2	NM:i:2	SM:i:0	XQ:i:0	X2:i:0	XO:Z:PM	XS:A:-
SRR073112.8947314	371	Chr02	76187	0	21M29H	=	75272	965	TTGCAACTGTGGTTCTAGGAA	;;FIIIIHIIIIIIIHIIIII	RG:Z:SRR073112	XH:Z:GTGCCGGGGATCATTGAATTAGGAATTAT	XI:Z:IIIIIIIIIIIIIIIIIIIIIIIIIIIII	MD:Z:21	NH:i:2	HI:i:2	NM:i:0	SM:i:0	XQ:i:0	X2:i:0	XO:Z:PM	XS:A:+	XT:Z:GT-AG,2.00,2.00,+Chr02@76187..-Chr05@25847531
SRR073112.8947314	67	Chr05	25847531	96	29M85N21M	=	25848531	965	ATAATTCCTAATTCAATGATCCCCGGCACTTCCTAGAACCACAGTTGCAA	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIHIIIIIIIHIIIIF;;	RG:Z:SRR073112	MD:Z:50	NH:i:2	HI:i:1	NM:i:0	SM:i:96	XQ:i:40	X2:i:0	XO:Z:PM	XS:A:-
SRR073112.8947314	355	Chr05	25847531	0	29M21H	Chr02	75272	965	ATAATTCCTAATTCAATGATCCCCGGCAC	IIIIIIIIIIIIIIIIIIIIIIIIIIIII	RG:Z:SRR073112	XH:Z:TTCCTAGAACCACAGTTGCAA	XI:Z:IIIIIHIIIIIIIHIIIIF;;	MD:Z:29	NH:i:2	HI:i:2	NM:i:0	SM:i:0	XQ:i:0	X2:i:0	XO:Z:PM	XS:A:-	XT:Z:GT-AG,2.00,2.00,+Chr02@76187..-Chr05@25847531
SRR073112.8947314	131	Chr05	25848531	96	50M	=	25847531	-965	TAAAAAGATAACTGCTGCCAATTCCCATCTTCTCATAAAGACGTTCACGT	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII8I:4@II	RG:Z:SRR073112	MD:Z:50	NH:i:2	HI:i:1	NM:i:0	SM:i:96	XQ:i:40	X2:i:0	XO:Z:PM	XS:A:+
```
and chromosomes sizes are
```
Chr02   25263035        51126598        80      81
Chr03   21816808        76705428        80      81
Chr04   24267051        98794954        80      81
Chr05   25890704        123365351       80      81
```

is this the same problem reported in https://github.com/AstraZeneca-NGS/VarDictJava/issues/7?

Thanks in advance

**Comment by mjafin** [comment]
Hi @inti it does look very similar. Once the new release is out please try it out first and if you still get the error let us know.
