### ISSUE TITLE
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1

### ISSUE THREAD

**Issue by NTNguyen13** [AstraZeneca-NGS/VarDictJava#281]
Hi, I currently have issue using VarDict in human genome file:

I use the command option from quick start:
```
VarDict -G /data4t/KHV1000G/refgen/hs37d5.fa.gz  \
   -f $AF_THR -N HG02142 \
   -b '/data4t/KHV1000G/aln/HG01595.mapped.ILLUMINA.bwa.KHV.low_coverage.20120522.bam'  \
   -N HG02142  \
   -c 1 -S 2 -E 3 \
   -R /data4t/KHV1000G/CDS100gene_padding.bed \
   -f $AF_THR>Vardict_test.vcf 

```
However there's a error:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
        at com.astrazeneca.vardict.RegionBuilder.buildRegionFromConfiguration(RegionBuilder.java:157)
        at com.astrazeneca.vardict.VarDictLauncher.initResources(VarDictLauncher.java:92)
        at com.astrazeneca.vardict.VarDictLauncher.start(VarDictLauncher.java:49)
        at com.astrazeneca.vardict.Main.main(Main.java:15)


```

What have gone wrong in my case? Thank you for your help

**Comment by luisacusick** [comment]
Hi, I am having a similar error -- did you figure out the solution?

Thanks!

Luisa

**Comment by PolinaBevad** [comment]
Hi @luisacusick , initial error appeared because option '-R' was used with the BED file instead of region in format `chr:start-end`. What is your command line?
