### ISSUE TITLE
-p fails with StringIndexOutOfBoundsException in amplicon mode

### ISSUE THREAD

**Issue by jasteen** [AstraZeneca-NGS/VarDictJava#285]
running 1.7.0
example command line.

`VarDict -G ${ref} -f 0.1 -N "${baseName}" -p --nosv -b ${bam} -c 1 -S 2 -E 3 -g 4 ${params.vardictBed} > "${baseName}.tsv"`

when an 8 column bed is supplied for amplicon mode, I get the following errors (only one chosen for simplicity, but I get enough to crash entirely)

```
There was Exception while processing position on 94153271 on region 11:94153228-94153388. The processing will be continued from the next position.
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.String.charAt(String.java:658)
        at com.astrazeneca.vardict.variations.Variant.adjComplex(Variant.java:224)
        at com.astrazeneca.vardict.postprocessmodules.AmpliconPostProcessModule.process(AmpliconPostProcessModule.java:190)
        at com.astrazeneca.vardict.modes.AmpliconMode.notParallel(AmpliconMode.java:71)
        at com.astrazeneca.vardict.VarDictLauncher.start(VarDictLauncher.java:65)
        at com.astrazeneca.vardict.Main.main(Main.java:15)

```

I get no errors and the program finishes normally if a 4 column bed is supplied.

not sure the best way to recreate as a minimal example.

**Comment by jasteen** [comment]
I've done a little more digging (with both the java version and the perl version) and it appears that variants that get flagged as "complex" are still not being handled correctly.  I think this is related to both java #265 and perl issue 130.

the perl version returns "0" as the reference base for complex variants when -p is supplied, which I expect is the same error that results in program termination in the java version.

running a very small test example on a single amplicon shows the following output for a number of "complex" variants in this pileup mode

```
test    MUTYH_1_F1      1       0       0       0       0       234     232     0       0       116     116     0       0.9915  2       68.0    1       30.0    1       60.0    3.143   1.0000  0       0       0       0       0.2176      176     0       0               Complex 0       0       0       0
test    MUTYH_1_F1      1       0       0       0       0       234     232     0       0       116     116     0       0.9915  2       68.0    1       35.2    1       60.0    45.400  1.0000  0       0       0       0       0.2227      227     0       0               Complex 0       0       0       0
test    MUTYH_1_F1      1       0       0       0       0       234     233     0       0       116     117     0       0.9957  2       30.5    1       34.4    1       60.0    22.300  1.0000  0       0       0       0       0.2223      223     0       0               Complex 0       0       0       0
test    MUTYH_1_F1      1       0       0       0       0       234     233     0       0       116     117     0       0.9957  2       35.0    1       34.2    1       60.0    14.533  1.0000  0       0       0       0       0.3218      218     0       0               Complex 0       0       0       0
test    MUTYH_1_F1      1       0       0       0       0       234     233     0       0       116     117     0       0.9957  2       50.5    1       33.7    1       60.0    11.944  1.0000  0       0       0       0       0.3215      215     0       0               Complex 0       0       0       0
test    MUTYH_1_F1      1       0       0       0       0       234     233     0       0       116     117     0       0.9957  2       51.5    1       33.1    1       60.0    7.962   1.0000  0       0       0       0       0.2207      207     0       0               Complex 0       0       0       0
test    MUTYH_1_F1      1       0       0       0       0       234     233     0       0       116     117     0       0.9957  2       67.0    1       34.6    1       60.0    22.300  1.0000  0       0       0       0       0.3223      223     0       0               Complex 0       0       0       0
test    MUTYH_1_F1      1       0       0       0       0       234     233     0       0       116     117     0       0.9957  2       67.5    1       32.9    1       60.0    8.708   1.0000  0       0       0       0       0.2209      209     0       0               Complex 0       0       0       0
test    MUTYH_1_F1      1       0       0       0       0       234     233     0       0       117     116     0       0.9957  2       33.0    1       34.4    1       60.0    22.300  1.0000  0       0       0       0       0.2223      223     0       0               Complex 0       0       0       0
test    MUTYH_1_F1      1       0       0       0       0       234     233     0       0       117     116     0       0.9957  2       36.0    1       34.9    1       60.0    32.286  1.0000  0       0       0       0       0.2226      226     0       0               Complex 0       0       0       0
test    MUTYH_1_F1      1       0       0       0       0       234     233     0       0       117     116     0       0.9957  2       37.0    1       33.5    1       60.0    10.650  1.0000  0       0       0       0       0.3213      213     0       0               Complex 0       0       0       0
test    MUTYH_1_F1      1       0       0       0       0       234     233     0       0       117     116     0       0.9957  2       45.0    1       34.8    1       60.0    22.300  1.0000  0       0       0       0       0.3223      223     0       0               Complex 0       0       0       0
test    MUTYH_1_F1      1       0       0       0       0       234     233     0       0       117     116     0       0.9957  2       48.0    1       34.5    1       60.0    22.300  1.0000  0       0       0       0       0.3223      223     0       0               Complex 0       0       0       0
test    MUTYH_1_F1      1       0       0       0       0       234     233     0       0       117     116     0       0.9957  2       50.0    1       34.8    1       60.0    32.286  1.0000  0       0       0       0       0.2226      226     0       0               Complex 0       0       0       0
test    MUTYH_1_F1      1       0       0       0       0       234     233     0       0       117     116     0       0.9957  2       56.0    1       33.8    1       60.0    11.944  1.0000  0       0       0       0       0.2215      215     0       0               Complex 0       0       0       0
test    MUTYH_1_F1      1       0       0       0       0       234     233     0       0       117     116     0       0.9957  2       65.5    1       33.4    1       60.0    11.944  1.0000  0       0       0       0       0.2215      215     0       0               Complex 0       0       0       0
test    MUTYH_1_F1      1       45794923        45794923        A       A       234     0       117     117     0       0       A/A     0       2;0     29.0    1       35.1    1       60.0    45.800  1.0000  0       0       0  00.3     229     229     0       0               SNV     0       1       0       0
test    MUTYH_1_F1      1       45794924        45794924        A       A       234     0       117     117     0       0       A/A     0       2;0     30.0    1       35.0    1       60.0    38.000  1.0000  0       0       0  00.3     228     228     0       0               SNV     0       1       0       0
test    MUTYH_1_F1      1       45794925        45794925        A       A       234     0       117     117     0       0       A/A     0       2;0     31.0    1       34.7    1       60.0    25.000  1.0000  0       0       0  00.3     225     225     0       0               SNV     0       1       0       0
test    MUTYH_1_F1      1       45794926        45794926        T       T       234     0       117     117     0       0       T/T     0       2;0     32.0    1       35.1    1       60.0    45.800  1.0000  0       0       0  00.3     229     229     0       0               SNV     0       1       0       0
test    MUTYH_1_F1      1       45794928        45794928        A       A       234     0       117     117     0       0       A/A     0       2;0     34.0    1       33.8    1       60.0    14.600  1.0000  0       0       0  00.3     219     219     0       0               SNV     0       1       0       0
test    MUTYH_1_F1      1       45794932        45794932        C       C       234     0       117     117     0       0       C/C     0       2;0     38.0    1       34.8    1       60.0    25.000  1.0000  0       0       0  00.3     225     225     0       0               SNV     0       1       0       0
test    MUTYH_1_F1      1       45794932        45794933        CT      C       234     2       116     116     1       1       T/-1    0.0085  2;2     40.0    1       36.0    0       60.0    4.000   0.0090  0       2       3.00
0       1       1.0     2       223     AATAACTACAAAAATAAGCA    TTACTAACAACAGGATTCTC    1:45794888-45795052     Deletion        1       1       0       0
test    MUTYH_1_F1      1       45794934        45794934        T       A       234     2       116     116     1       1       T/A     0.0085  2;2     40.0    1       36.0    0       60.0    4.000   0.0091  0       0       3.00
0       1       1.0     2       219     TAACTACAAAAATAAGCACT    TACTAACAACAGGATTCTCA    1:45794888-45795052     SNV     1       1       0       0
test    MUTYH_1_F1      1       45794935        45794935        T       T       234     0       117     117     0       0       T/T     0       2;0     41.0    1       34.2    1       60.0    22.400  1.0000  0       0       0  00.3     224     224     0       0               SNV     0       1       0       0
test    MUTYH_1_F1      1       45794936        45794936        A       A       234     0       117     117     0       0       A/A     0       2;0     42.0    1       35.1    1       60.0    45.800  1.0000  0       0       0  00.3     229     229     0       0               SNV     0       1       0       0
test    MUTYH_1_F1      1       45794937        45794937        C       C       234     0       117     117     0       0       C/C     0       2;0     43.0    1       35.1    1       60.0    57.500  1.0000  0       0       0  00.3     230     230     0       0               SNV     0       1       0       0
test    MUTYH_1_F1      1       45794938        45794938        T       T       234     0       117     117     0       0       T/T     0       2;0     44.0    1       33.2    1       60.0    10.143  1.0000  0       0       0  00.3     213     213     0       0               SNV     0       1       0       0
test    MUTYH_1_F1      1       45794940        45794940        A       A       234     0       117     117     0       0       A/A     0       2;0     46.0    1       32.8    1       60.0    6.800   1.0000  0       0       0  00.3     204     204     0       0               SNV     0       1       0       0
test    MUTYH_1_F1      1       45794941        45794941        C       C       234     0       117     117     0       0       C/C     0       2;0     47.0    1       34.7    1       60.0    22.400  1.0000  0       0       0  00.3     224     224     0       0               SNV     0       1       0       0
test    MUTYH_1_F1      1       45794943        45794943        A       A       234     0       117     117     0       0       A/A     0       2;0     49.0    1       33.4    1       60.0    9.636   1.0000  0       0       0  00.3     212     212     0       0               SNV     0       1       0       0
```
as you can see the reference base is given a 0 instead of [AGTC].  I assume these are variants with a single very low quality sequencing/PCR errorqls

NOTE:  This only occurs with `-p -a`. when I remove the last 4 columns from the bed file it runs fine.

**Comment by PolinaBevad** [comment]
Hi Jason! 

Could you please share part of BAM and amplicon BED where this occurs so I can check what is the problem? We don't have a lot of amplicon test data, so it will be very helpful!

**Comment by jasteen** [comment]
the following command line will replicate the issue on the the files located at this google drive `https://drive.google.com/open?id=1bzcwtbBnwlWuRztxLmltTAgLW-gdI3C6`

`VarDict -G human_g1k_v37_decoy.fasta -f 0.1 -N "test" --nosv -p -b MRE11a.bam -c 1 -S 2 -E 3 -g 4 test.amplicon.MRE11A.8col.bed > "test.tsv"`

**Comment by PolinaBevad** [comment]
Hi Jason! 

Thank you for finding this issue!
I figured out what is the problem: we don't have full information for reference alleles in pileup mode, so I've added fix in corresponding PR. 
I'm not sure it will be merged and released this week, but if it is critical for your pipeline, you can build this from PR branch!

**Comment by jasteen** [comment]
Hi @PolinaBevad . thanks very much for this.  i've built the PR branch from your repo, and it works perfectly on both the test data and my actual samples.  cheers.

Jason

**Comment by PolinaBevad** [comment]
Hi Jason, I'll close this issue as it was merged!
