### ISSUE TITLE
why can I use "qsub" to run the VarDict task?

### ISSUE THREAD

**Issue by windtalker6** [AstraZeneca-NGS/VarDictJava#322]
`#!/bin/sh
#$ -S /bin/sh

#https://github.com/AstraZeneca-NGS/VarDictJava
export PATH="/path/01.Program/Scripts/02.software/VarDictJava/build/install/VarDict/bin":$PATH
echo -n "Start: ";date +%Y-%m-%d%t%H:%M:%S
perl /path/01.Program/Scripts/01.script/GeneLab/CheckStepNormalTermination.pl /path/03.Clinical_Data/11.PanCancer/01.Germline/sh.e.o/Patient-normal_XXX_DX0503/R02.BqsrApply.Patient-normal_XXX_DX0503.sh --standardOut End --standardError error

AF_THR="0.01" # minimum allele frequency
VarDict -G /path/01.Program/Scripts/02.software/GATK/fasta_index/hg19.fa -f $AF_THR -N Patient_XXX_DX0503 -b "/path/03.Clinical_Data/11.PanCancer/02.Somatic/02.SortMarkdupBqsrApply/Patient_XXX_DX0503/Patient_XXX_DX0503.marked_duplicates.bam|/path/03.Clinical_Data/11.PanCancer/01.Germline/02.SortMarkdupBqsrApply/Patient-normal_XXX_DX0503/Patient-normal_XXX_DX0503.marked_duplicates.bam" -c 1 -S 2 -E 3 -g 4 -th 6 /path/01.Program/Scripts/02.software/GATK/bed/test/DX0503.flank100.bed|testsomatic.R |var2vcf_paired.pl -N "Patient_XXX_DX0503|Patient-normal_XXX_DX0503" -f $AF_THR >/path/03.Clinical_Data/11.PanCancer/02.Somatic/03.MuTect2/Patient_XXX_DX0503/Patient_XXX_DX0503.vardict.markdup_bam.thread6.vcf
echo -n "End: ";date +%Y-%m-%d%t%H:%M:%S
`

my code is as above, and I use the command below to submit my task:

qsub -cwd -V -q genelab.q -pe smp 7 -l h_vmem=30G -e /path/03.Clinical_Data/11.PanCancer/02.Somatic/sh.e.o/Patient_XXX_DX0503/vcf_split/R03.VarDict.sh.e -o /path/03.Clinical_Data/11.PanCancer/02.Somatic/sh.e.o/Patient_XXX_DX0503/vcf_split/R03.VarDict.sh.o /path/03.Clinical_Data/11.PanCancer/02.Somatic/sh.e.o/Patient_XXX_DX0503/vcf_split/R03.VarDict.sh

and I always got the error:

========================================================================
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/astrazeneca/vardict/Main : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

========================================================================

how can I solve this?

**Comment by PolinaBevad** [comment]
Hi @windtalker6 ,

This error shows that you have Java JRE 6 or 7 installed in your system instead of 8+. We support only Java from 8th version, so please try to reinstall it/load module if your run it on cluster, and also check what version of Java you have in path for gsub.

**Comment by PolinaBevad** [comment]
Hi @windtalker6, I guess this issue can be closed! Let me know if you are still facing this problem, will try to help you!
Thanks!
