### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by marrip** [AstraZeneca-NGS/VarDictJava#338]
Hi, I am running VarDict with the following command:

```
VarDict -G Ref.fasta -f 0.01 -N NA12878 -b NA12878.bam -c 1 -S 2 -E 3 -g 4 wgs.bed
```

and get an error immediately

```
Exception in thread "main" java.lang.NumberFormatException: For input string: "VN:1.5"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:652)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at com.astrazeneca.vardict.Utils.toInt(Utils.java:91)
        at com.astrazeneca.vardict.RegionBuilder.buildRegions(RegionBuilder.java:65)
        at com.astrazeneca.vardict.VarDictLauncher.initResources(VarDictLauncher.java:102)
        at com.astrazeneca.vardict.VarDictLauncher.start(VarDictLauncher.java:49)
        at com.astrazeneca.vardict.Main.main(Main.java:15)
```

I checked my bam header and could not find `VN:1.5`. Does anyone have any idea what causes this error? Cheers!

**Comment by marrip** [comment]
I realized it is caused by my `bed` file...sorry.

**Comment by marrip** [comment]
I realized it is caused by my `bed` file...sorry.
