### ISSUE TITLE
No line found error in the java version, works in the perl version

### ISSUE THREAD

**Issue by rglusic** [AstraZeneca-NGS/VarDictJava#359]
Hello, one of the researchers at my institution has been running into an issue when trying to run VarDict. The below error is only present within the Java version of VarDict and does not error out within the perl version. We have tried multiple fasta files and the issue still remains. The problem occurs before teststrandbias.R runs.

```
VarDict -G human_g1k_v37.fasta -N 1seracare0p1-1hyb68-rep1 -f 0.01 -b 1seracare0p1-1hyb68-rep1_bwa.TP53.sort.bam -c 1 -S 2 -E 3 TP53_Multiplicom.BED -U | teststrandbias.R | var2vcf_valid.pl -N 7CYCOLOEZ100_tumor -E -f 0.01 > 7CYCOLOEZ100_tumor.vcf
```

```
Critical exception occurs on region: 17:7572834-7573032, program will be stopped.
java.util.NoSuchElementException: No line found
	at java.util.Scanner.nextLine(Scanner.java:1540)
	at htsjdk.samtools.reference.FastaSequenceIndex.parseIndexFile(FastaSequenceIndex.java:161)
	at htsjdk.samtools.reference.FastaSequenceIndex.<init>(FastaSequenceIndex.java:72)
	at htsjdk.samtools.reference.IndexedFastaSequenceFile.<init>(IndexedFastaSequenceFile.java:71)
	at com.astrazeneca.vardict.data.ReferenceResource.lambda$fetchFasta$0(ReferenceResource.java:34)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
	at com.astrazeneca.vardict.data.ReferenceResource.fetchFasta(ReferenceResource.java:30)
	at com.astrazeneca.vardict.data.ReferenceResource.retrieveSubSeq(ReferenceResource.java:52)
	at com.astrazeneca.vardict.data.ReferenceResource.getReference(ReferenceResource.java:94)
	at com.astrazeneca.vardict.data.ReferenceResource.getReference(ReferenceResource.java:74)
	at com.astrazeneca.vardict.modes.AbstractMode.tryToGetReference(AbstractMode.java:153)
	at com.astrazeneca.vardict.modes.SimpleMode.processBamInPipeline(SimpleMode.java:98)
	at com.astrazeneca.vardict.modes.SimpleMode.notParallel(SimpleMode.java:45)
	at com.astrazeneca.vardict.VarDictLauncher.start(VarDictLauncher.java:65)
	at com.astrazeneca.vardict.Main.main(Main.java:15)
```

**Comment by rglusic** [comment]
We discovered that the issue was a corrupted set of .fasta files and their indexes
