### ISSUE TITLE
VarDict producing illegal CIGAR strings in modifyCigar method and crashing

### ISSUE THREAD

**Issue by haseley** [AstraZeneca-NGS/VarDictJava#37]
Hello,

When processing the attached bam (contains a single well-formatted read), using hg38 as a reference, VarDict produces a malformed cigar string with a negative number, causing samtools to throw an illegal argument exception.

java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Malformed CIGAR string: 3S38M6D-6I115M
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.astrazeneca.vardict.VarDict.vardictParallel(VarDict.java:286)
	at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:256)
	at com.astrazeneca.vardict.VarDict.start(VarDict.java:65)
	at com.astrazeneca.vardict.Main.run(Main.java:134)
	at com.astrazeneca.vardict.Main.main(Main.java:25)

Command: VarDict -G ./hg38.fa -b "problem.bam" -N "problem" -c 1 -S 2 -E 3 -g 4 problem.bed > out.txt

[Downloads.zip](https://github.com/AstraZeneca-NGS/VarDictJava/files/253124/Downloads.zip)

**Comment by mjafin** [comment]
Hi @haseley sorry about the problem and thanks for reporting this. @jabbarish would you and the team be able to take a look at this when you have the time?

**Comment by jabbarish** [comment]
Hi @mjafin!  Sure. We will reply soon.

**Comment by jabbarish** [comment]
It seems that invalid cigar is produced in the modifyCigar method  in the case of replacement M-D-M-I-M-D complex with M-D-I.   @zhongwulai , please have a look.

**Comment by JoKw** [comment]
Hi @jabbarish, Is there a fix for the problem? I got the error too. 
Exception in thread "main" java.lang.IllegalArgumentException: Malformed CIGAR string: 71M12D-1I30M
        at htsjdk.samtools.TextCigarCodec.decode(TextCigarCodec.java:69)
        at com.astrazeneca.vardict.VarDict.parseSAM(VarDict.java:1550)
        at com.astrazeneca.vardict.VarDict.toVars(VarDict.java:2552)
        at com.astrazeneca.vardict.VarDict.somaticNotParallel(VarDict.java:353)
        at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:249)
        at com.astrazeneca.vardict.VarDict.start(VarDict.java:65)
        at com.astrazeneca.vardict.Main.run(Main.java:134)
        at com.astrazeneca.vardict.Main.main(Main.java:25)

**Comment by zhongwulai** [comment]
The issue was caused when VarDict tries to fix a way inferior alignment the aligner produced.  The original CIGAR 3S18M4D4M8I2M16D115M, should be as simple as "3S38M12D109M".  Looking at the header, the aligner "isaac-align" has not been tested by VarDict.  Maybe you should also try to contact the author of the aligner for a fix?

Meanwhile, I push the fix for Perl version in github (lines 751-783 clause) and it should be fine now for such error.  Zaal, please update the Java version.

Thanks!
Zhongwu

**Comment by jabbarish** [comment]
Thanks!

**Comment by mjafin** [comment]
Thanks Zhongwu, much appreciated for looking into this. I reported the issue with Illumina and will close this ticket.

**Comment by jabbarish** [comment]
@JoKw Could you provide us with a data to test our fix, please?

**Comment by mjafin** [comment]
@haseley can you check suggestion by @rpetrovski at https://github.com/Illumina/isaac2/issues/15
