### ISSUE TITLE
cram input

### ISSUE THREAD

**Issue by GSBaohuaGu** [AstraZeneca-NGS/VarDictJava#380]
I tried the method you mentioned  solve the problem if the input is cram format, but still reported an error.
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/compress/compressors/bzip2/BZip2CompressorOutputStream
	at htsjdk.samtools.cram.structure.block.Block.getUncompressedContent(Block.java:203)
	at htsjdk.samtools.cram.build.CramIO.readSAMFileHeader(CramIO.java:316)
	at htsjdk.samtools.cram.build.CramIO.readCramHeader(CramIO.java:225)
	at htsjdk.samtools.cram.build.CramContainerIterator.<init>(CramContainerIterator.java:22)
	at htsjdk.samtools.CRAMIterator.<init>(CRAMIterator.java:86)
	at htsjdk.samtools.CRAMFileReader.initWithStreams(CRAMFileReader.java:226)
	at htsjdk.samtools.CRAMFileReader.<init>(CRAMFileReader.java:219)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:422)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:208)
	at com.astrazeneca.vardict.VarDictLauncher.readChr(VarDictLauncher.java:187)
	at com.astrazeneca.vardict.VarDictLauncher.initResources(VarDictLauncher.java:80)
	at com.astrazeneca.vardict.VarDictLauncher.start(VarDictLauncher.java:49)
	at com.astrazeneca.vardict.Main.main(Main.java:15)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.compressors.bzip2.BZip2CompressorOutputStream
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 13 more

**Comment by karlestira** [comment]
you can download a new htsjdk and build it (using IntelliJ IDEA to build with command ./gradlew shadowJar, the zip file is htsjdk 3.0.5), and use CLASSPATH=<htsjdk.jar>:<vardict.jar> when launch JVM. This will replace htsjdk inner vardict with your new htsjdk and fix dependency problem.
[htsjdk-3.0.5.jar.zip](https://github.com/AstraZeneca-NGS/VarDictJava/files/11278867/htsjdk-3.0.5.jar.zip)
