### ISSUE TITLE
VCF merging between Mutect2 and VarDict output fail

### ISSUE THREAD

**Issue by lmanchon** [AstraZeneca-NGS/VarDictJava#382]
java --jar $PICARD MergeVcfs I=${lib}"_Mutect2.vcf.gz" I=${lib}"_vardict.vcf.gz" O=${lib}"_picard_Variants.vcf.gz"
INFO    2023-03-09 15:33:31     MergeVcfs

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    MergeVcfs -I GATK/HD829_S1_Mutect2.vcf.gz -I VARDICT/HD829_S1_vardict.vcf.gz -O SNV/HD829_S1_picard_Variants.vcf.gz
**********

15:33:33.908 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/usr/local/bioinfo/src/picard-tools/picard-2.20.7/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Thu Mar 09 15:33:34 CET 2023] MergeVcfs INPUT=[GATK/HD829_S1_Mutect2.vcf.gz, VARDICT/HD829_S1_vardict.vcf.gz] OUTPUT=SNV/HD829_S1_picard_Variants.vcf.gz    VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=true CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Thu Mar 09 15:33:34 CET 2023] Executing as sassou@node107 on Linux 3.10.0-1160.el7.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 15.0.1+9-18; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.20.7-SNAPSHOT
[Thu Mar 09 15:33:34 CET 2023] picard.vcf.MergeVcfs done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=32440320
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.IllegalArgumentException: The contig entries in input file VARDICT/HD829_S1_vardict.vcf.gz are not compatible with the others.
        at picard.vcf.MergeVcfs.doWork(MergeVcfs.java:189)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)

**Comment by PolinaBevad** [comment]
Hi @lmanchon, I believe it is not just VarDict issue. There is a difference between contig names used in both VCF files, please check that you used the same references for both of them.

**Comment by lmanchon** [comment]
right, i use recalibrated bam for Mutect2 and not recalibrated bam for Vardict. 
Do you think it's necessary to recalibrate bam file for Vardict ?
