### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by pagnasok** [AstraZeneca-NGS/VarDictJava#393]
Hello,

I have a script that is running in the normal-tumor pair mode. It seems to be running fine but stopped after running into issues in a specific region, which is 1_KN196472v1_fix:111106-133486. I tried to debug but am not sure what is the problem. I am not sure if this is a problem with the BAM files or the Fasta file. Can you help resolve this?

This is the error log:

Critical exception occurs on region: 1_KN196472v1_fix:111106-133486, program will be stopped.
com.astrazeneca.vardict.exception.RegionBoundariesException: The region 1_KN196472v1_fix:109906-0 is wrong. We have problem while reading it, possible the start is after the end of the region or the fasta doesn't contain this region.
	at com.astrazeneca.vardict.data.ReferenceResource.retrieveSubSeq(ReferenceResource.java:60)
	at com.astrazeneca.vardict.data.ReferenceResource.getReference(ReferenceResource.java:94)
	at com.astrazeneca.vardict.data.ReferenceResource.getReference(ReferenceResource.java:74)
	at com.astrazeneca.vardict.modes.AbstractMode.tryToGetReference(AbstractMode.java:153)
	at com.astrazeneca.vardict.modes.SomaticMode.notParallel(SomaticMode.java:48)
	at com.astrazeneca.vardict.VarDictLauncher.start(VarDictLauncher.java:65)
	at com.astrazeneca.vardict.Main.main(Main.java:15)
Caused by: htsjdk.samtools.SAMException: Malformed query; start point 109906 lies after end point 0
	at htsjdk.samtools.reference.AbstractIndexedFastaSequenceFile.getSubsequenceAt(AbstractIndexedFastaSequenceFile.java:175)
	at htsjdk.samtools.reference.IndexedFastaSequenceFile.getSubsequenceAt(IndexedFastaSequenceFile.java:49)
	at com.astrazeneca.vardict.data.ReferenceResource.retrieveSubSeq(ReferenceResource.java:53)
	... 6 more

Thanks!

**Comment by anastasiaprime** [comment]
Hello,       

I have the same problem. Did you solve this?

**Comment by anastasiaprime** [comment]
I run script in the single mode by this command:

VarDict -G /mnt/cephfs8_rw/oncology/refdata-GRCh38-2.1.0/fasta/genome.fa -f 0.01 -N sample_1 -b vcf/772015181601_S2_dedup_chr22_bsqr.bam -c 1 -S 2 -E 3 bins.bed | /root/VarDictJava/build/install/VarDict/bin/teststrandbias.R | /root/VarDictJava/build/install/VarDict/bin/var2vcf_valid.pl -N sample_1 -E -f 0.01 > vars.vcf

The error log is:

Critical exception occurs on region: chr"chr1":764620-864620, program will be stopped.
com.astrazeneca.vardict.exception.RegionBoundariesException: The region chr"chr1":763420-0 is wrong. We have problem while reading it, possible the start is after the end of the region or the fasta doesn't contain this region.
	at com.astrazeneca.vardict.data.ReferenceResource.retrieveSubSeq(ReferenceResource.java:60)
	at com.astrazeneca.vardict.data.ReferenceResource.getReference(ReferenceResource.java:94)
	at com.astrazeneca.vardict.data.ReferenceResource.getReference(ReferenceResource.java:74)
	at com.astrazeneca.vardict.modes.AbstractMode.tryToGetReference(AbstractMode.java:153)
	at com.astrazeneca.vardict.modes.SimpleMode.processBamInPipeline(SimpleMode.java:98)
	at com.astrazeneca.vardict.modes.SimpleMode.notParallel(SimpleMode.java:45)
	at com.astrazeneca.vardict.VarDictLauncher.start(VarDictLauncher.java:65)
	at com.astrazeneca.vardict.Main.main(Main.java:15)
Caused by: htsjdk.samtools.SAMException: Malformed query; start point 763420 lies after end point 0
	at htsjdk.samtools.reference.AbstractIndexedFastaSequenceFile.getSubsequenceAt(AbstractIndexedFastaSequenceFile.java:175)
	at htsjdk.samtools.reference.IndexedFastaSequenceFile.getSubsequenceAt(IndexedFastaSequenceFile.java:49)
	at com.astrazeneca.vardict.data.ReferenceResource.retrieveSubSeq(ReferenceResource.java:53)
	... 7 more


The first region is not even start with 763420, it starts with 764620 like in first error message. Can someone help me?
