### ISSUE TITLE
StringIndexOutOfBoundsException: String index out of range: 1

### ISSUE THREAD

**Issue by leon8889** [AstraZeneca-NGS/VarDictJava#48]
I get this error while running VarDict:
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 1
	at java.lang.String.charAt(String.java:658)
	at com.astrazeneca.vardict.VarDict.parseSAM(VarDict.java:2221)
	at com.astrazeneca.vardict.VarDict.toVars(VarDict.java:2552)
	at com.astrazeneca.vardict.VarDict.vardictNotParallel(VarDict.java:301)
	at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:254)
	at com.astrazeneca.vardict.VarDict.start(VarDict.java:65)
	at com.astrazeneca.vardict.Main.run(Main.java:134)
	at com.astrazeneca.vardict.Main.main(Main.java:25)
Argument "0,0909" isn't numeric in numeric lt (<) at /home/kua/Downloads/Installer/CNVtools/VarDict-1.4.6/VarDict/var2vcf_valid.pl line 124, <> line 71.
Argument "124,5" isn't numeric in numeric lt (<) at /home/kua/Downloads/Installer/CNVtools/VarDict-1.4.6/VarDict/var2vcf_valid.pl line 125, <> line 71.
Argument "93,0" isn't numeric in numeric lt (<) at /home/kua/Downloads/Installer/CNVtools/VarDict-1.4.6/VarDict/var2vcf_valid.pl line 127, <> line 71.
Argument "0,0" isn't numeric in numeric lt (<) at /home/kua/Downloads/Installer/CNVtools/VarDict-1.4.6/VarDict/var2vcf_valid.pl line 128, <> line 71.
....

Could you please help me??

**Comment by mjafin** [comment]
Hi @leon8889,
It seems like VarDictJava is failing for one reason or another. May I ask you how you aligned your data (bwa-mem?) and if you performed any external (indel)realignment?
