### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ltfang-bina** [AstraZeneca-NGS/VarDictJava#6]
I have seen the following exit message on error:

Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.charAt(String.java:658)
	at com.astrazeneca.vardict.VarDict.modifyCigar(VarDict.java:6065)
	at com.astrazeneca.vardict.VarDict.parseSAM(VarDict.java:1529)
	at com.astrazeneca.vardict.VarDict.toVars(VarDict.java:2515)
	at com.astrazeneca.vardict.VarDict.somaticNotParallel(VarDict.java:356)
	at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:251)
	at com.astrazeneca.vardict.VarDict.start(VarDict.java:67)
	at com.astrazeneca.vardict.Main.run(Main.java:137)
	at com.astrazeneca.vardict.Main.main(Main.java:24)

I have two small BAM files of 1.5 MB each in size that can reproduce this error. 

Command used were:
VarDictJava/build/install/VarDict/bin/VarDict -G human_g1k_v37_decoy.fasta -f 0.01 -h -b 'tumor.errored.bam|normal.errored.bam' -C -c 1 -S 2 -E 3 -g 4 errored.5kbps.bed 2> errored.msg > errored.var

Is there a way I can get the BAM files to you guys?

Thanks.

**Comment by zhongwulai** [comment]
Li Tai,

It might be the same problem that we discussed, where a read is aligned in a stretch of Ns.  Can you check whether it's the case?  You can send BAM files through email.  1.5 MB should be OK.

Thanks,
Zhongwu
