### ISSUE TITLE
Error: Did not inflate expected amount

### ISSUE THREAD

**Issue by tamaraprieto** [AstraZeneca-NGS/VarDictJava#61]
I am getting the error below when running the program but only for some tumor samples: 

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: htsjdk.samtools.SAMFormatException: Did not inflate expected amount
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.astrazeneca.vardict.VarDict.somaticParallel(VarDict.java:338)
	at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:251)
	at com.astrazeneca.vardict.VarDict.start(VarDict.java:65)
	at com.astrazeneca.vardict.Main.run(Main.java:134)
	at com.astrazeneca.vardict.Main.main(Main.java:25)
Caused by: java.util.concurrent.ExecutionException: htsjdk.samtools.SAMFormatException: Did not inflate expected amount
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.astrazeneca.vardict.VarDict$SomdictWorker.call(VarDict.java:5356)
	at com.astrazeneca.vardict.VarDict$SomdictWorker.call(VarDict.java:5339)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: htsjdk.samtools.SAMFormatException: Did not inflate expected amount
	at htsjdk.samtools.util.BlockGunzipper.unzipBlock(BlockGunzipper.java:98)
	at htsjdk.samtools.util.BlockCompressedInputStream.inflateBlock(BlockCompressedInputStream.java:402)
	at htsjdk.samtools.util.BlockCompressedInputStream.readBlock(BlockCompressedInputStream.java:384)
	at htsjdk.samtools.util.BlockCompressedInputStream.available(BlockCompressedInputStream.java:127)
	at htsjdk.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:252)
	at java.io.DataInputStream.read(DataInputStream.java:149)
	at htsjdk.samtools.util.BinaryCodec.readBytesOrFewer(BinaryCodec.java:404)
	at htsjdk.samtools.util.BinaryCodec.readBytes(BinaryCodec.java:380)
	at htsjdk.samtools.util.BinaryCodec.readByteBuffer(BinaryCodec.java:490)
	at htsjdk.samtools.util.BinaryCodec.readInt(BinaryCodec.java:501)
	at htsjdk.samtools.BAMRecordCodec.decode(BAMRecordCodec.java:177)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.getNextRecord(BAMFileReader.java:661)
	at htsjdk.samtools.BAMFileReader$BAMFileIndexIterator.getNextRecord(BAMFileReader.java:781)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:635)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:629)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:599)
	at htsjdk.samtools.BAMFileReader$BAMQueryFilteringIterator.advance(BAMFileReader.java:832)
	at htsjdk.samtools.BAMFileReader$BAMQueryFilteringIterator.next(BAMFileReader.java:822)
	at htsjdk.samtools.BAMFileReader$BAMQueryFilteringIterator.next(BAMFileReader.java:788)
	at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:544)
	at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:518)
	at com.astrazeneca.vardict.VarDict$SamView.read(VarDict.java:1343)
	at com.astrazeneca.vardict.VarDict.parseSAM(VarDict.java:1401)
	at com.astrazeneca.vardict.VarDict.toVars(VarDict.java:2552)
	at com.astrazeneca.vardict.VarDict$ToVarsWorker.call(VarDict.java:5334)
	at com.astrazeneca.vardict.VarDict$ToVarsWorker.call(VarDict.java:5308)
	... 4 more

This is the command line I have runned:
```
VarDict \
        -G ref.fa \
        -D \
        -b "tumor.bam|control.bam" \
        -z $BED_Z \
        -q $QUAL \
        -Q 10 \
        -F $FILTER \
        -f $AF_THR \
        -c 1 -S 2 -E 3 -g 4 \
        chunkstarget.bed \
        | /opt/cesga/vardictjava/VarDictJava-master/VarDict/testsomatic.R \
        | /opt/cesga/vardictjava/VarDictJava-master/VarDict/var2vcf_paired.pl -N "tumor|control" -f $AF_THR  -P 0.9 -m 4.25 > ${WORKDIR}/VarDict.tumor.vcf
```

The bam files have been validated and they do not show any error

**Comment by mjafin** [comment]
Hi @tamaraprieto, thanks for trying VarDict and sorry about the problems. So you're absolutely positive that the bam files are not corrupted (https://github.com/samtools/samtools/issues/362) ? 

I saw a mention of high Phred scores. Could it be your quality values are in Illumina instead of Sanger format?

**Comment by tamaraprieto** [comment]
Hi @mjafin, thank you for the quick response. I have validated them using Picard ValidateSamFiles but in fact, as my bam files have been generated by an IonProton platform one months ago I assumed they would be in Sanger format. I will check it because in fact I got another error in one of the samples that claims Cannot encode phred score: 102. It is probably what you are saying. Thank you very much

**Comment by mjafin** [comment]
OK well let us know what you find out. I'll close the issue but please reopen if your problem isn't with the quality values after all. A small slice of a bam file that causes the issue would be very helpful for our debugging.

**Comment by tamaraprieto** [comment]
Hi again @mjafin. I have checked the encoding and the files seems to be Sanger/ Illumina 1.9 so it has to be another reason... I attach a subsampling of the bam file for debugging

[tumor.bam.zip](https://github.com/AstraZeneca-NGS/VarDictJava/files/727163/tumor.bam.zip)

**Comment by mjafin** [comment]
@ZLyanov would your team be able to take a quick look at this when you've the cycles? This is Ion Proton data so something we rarely if ever look at.

**Comment by kamyshova** [comment]
@tamaraprieto could you tell us please which reference was used. A small slice of control.bam would be also very helpful.

**Comment by tamaraprieto** [comment]
[control.bam.zip](https://github.com/AstraZeneca-NGS/VarDictJava/files/732707/control.bam.zip)

Hi @kamyshova, 
Here you are the control. The reference is the default in torrent browser (3G), how do you prefer I share it?

**Comment by kamyshova** [comment]
Do you mean this is hg19?
Could you send a link or screenshot of torrent browser (3G)?

**Comment by tamaraprieto** [comment]
Hi again @kamyshova, 

It is hg19 but but with some modifications. I do not have access to Torrent browser, my collaborators shared with me the reference but the link has already expired. However, I think it is the same that the 8th entry (description:Homo sapiens hg19) in [here](https://ts-pgm.epigenetic.ru/configure/references/). 

It shouls be like this:
`SN:chr1 LN:249250621
SN:chr2 LN:243199373
SN:chr3 LN:198022430
SN:chr4 LN:191154276
SN:chr5 LN:180915260
SN:chr6 LN:171115067
SN:chr7 LN:159138663
SN:chr8 LN:146364022
SN:chr9 LN:141213431
SN:chr10 LN:135534747
SN:chr11 LN:135006516
SN:chr12 LN:133851895
SN:chr13 LN:115169878
SN:chr14 LN:107349540
SN:chr15 LN:102531392
SN:chr16 LN:90354753
SN:chr17 LN:81195210
SN:chr18 LN:78077248
SN:chr19 LN:59128983
SN:chr20 LN:63025520
SN:chr21 LN:48129895
SN:chr22 LN:51304566
SN:chrX LN:155270560
SN:chrY LN:59373566
SN:chrM LN:16569`

Otherwise, I can download  it from the cluster and upload it to dropbox or mega and share it with you.

**Comment by kamyshova** [comment]
@tamaraprieto thank you for providing files. We've run them with parameters that are clearly defined in your command line example. 
Surprisingly, it has completed without exceptions. 
We probably need a 100% synchronized run.
Could you please share the whole set of parameters as well as a BED file?

**Comment by tamaraprieto** [comment]
@kamyshova sorry for the delay but I was out of the office and the internet connection was very bad. Here you have [all the files](https://www.dropbox.com/sh/w0q87klkaxlnoqj/AADQe08m_bTSozfuff5YbVeRa?dl=0). I think you cannot download them as a zip but it should work one by one. 

These are the parameters:
```
AF_THR="0.01"
QUAL=15
FILTER="0x100" 
BED_Z=1

VarDict \
        -G ref.fa \
        -D \
        -b "tumor.bam|control.bam" \
        -z $BED_Z \
        -q $QUAL \
        -Q 10 \
        -F $FILTER \
        -f $AF_THR \
        -c 1 -S 2 -E 3 -g 4 \
        chunkstarget.bed \
        | /opt/cesga/vardictjava/VarDictJava-master/VarDict/testsomatic.R \
        | /opt/cesga/vardictjava/VarDictJava-master/VarDict/var2vcf_paired.pl -N "tumor|control" -f $AF_THR  -P 0.9 -m 4.25 > ${WORKDIR}/VarDict.tumor.vcf
```

**Comment by kamyshova** [comment]
@tamaraprieto we've checked VarDict ones again with your parameters and it finished without any exceptions. Maybe there are problems with index files. How did you build them for reference and bam files?

**Comment by mjafin** [comment]
If the bed file has too many regions included it could also be a RAM issue. I haven't got access to the bed file but does it have multiple chromosomes or just a few chunks here and there? VarDict should be run on smaller chunks

**Comment by tamaraprieto** [comment]
Hi @kamyshova and @mjafin. Thanks for your help. The bam index files have been generated in the sequencing center and I have run these two commands for the reference. 

```
java -jar picard.jar CreateSequenceDictionary R=ref.fa O=ref.dict
samtools faidx ref.fa
```

The bed file is [this one](https://www.dropbox.com/s/vth05w2srzf4dnz/chunkstarget.bed?dl=0) and it has 351 amplicons (~120bp) covering 17 genes. 

I will run everything after creating the bam index files myself, just to check. I will tell you something when I have some news.

**Comment by tamaraprieto** [comment]
Hi, I still don't have an answer to the error but I think is something related to the cluster where I am running the code. Some jobs fail but when I run them independently they work. And different jobs fail each time. Anyway, I got all my jobs finished without errors at least once so you can close the issue. Thank you very much for your help. 

Tamara

**Comment by mjafin** [comment]
Hi Tamara, thanks for confirming. These intermittent gremlins are the worst. Hopefully your admins can figure out if it's a problem with the amount of RAM or something as simple as the maximum allowed open file / process handles.
