### ISSUE TITLE
Do not fail on single end data with new overlapping read support

### ISSUE THREAD

**Issue by chapmanb** [AstraZeneca-NGS/VarDictJava#63]
The latest release (1.4.9) fails when using single end read data during the check for overlaps:
```
Exception in thread "main" java.lang.IllegalStateException: Inappropriate call if not paired read
        at htsjdk.samtools.SAMRecord.requireReadPaired(SAMRecord.java:871)
        at htsjdk.samtools.SAMRecord.getMateNegativeStrandFlag(SAMRecord.java:917)
        at com.astrazeneca.vardict.VarDict.isReadsOverlap(VarDict.java:2520)
        at com.astrazeneca.vardict.VarDict.parseSAM(VarDict.java:1600)
        at com.astrazeneca.vardict.VarDict.toVars(VarDict.java:2603)
        at com.astrazeneca.vardict.VarDict.vardictNotParallel(VarDict.java:325)
        at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:278)
        at com.astrazeneca.vardict.VarDict.start(VarDict.java:89)
        at com.astrazeneca.vardict.Main.run(Main.java:134)
        at com.astrazeneca.vardict.Main.main(Main.java:25)
```
Ideally VarDict would detect that it's not paired data and skip the overlap check. Here is a small test case that demonstrates the issue:

http://s3.amazonaws.com/chapmanb/testcases/vardict_singleend.tar.gz

**Comment by ZLyanov** [comment]
@chapmanb thank you!  we will check whether it is a regression asap.

**Comment by SilinPavel** [comment]
@chapmanb Issue was resolved, please check! 
Here is the commit:
https://github.com/AstraZeneca-NGS/VarDictJava/commit/f34c8d0c807c48361179efc57cfe423e44c396d8

**Comment by chapmanb** [comment]
Pavel and Zaal -- brilliant, thank you for the quick fix. That does resolve it for me. Would it be possible to push a new release with the fix and I'll update the bioconda packages. Thanks again.

**Comment by ZLyanov** [comment]
@chapmanb Done.  See release 1.4.10
 Thanks!

**Comment by chapmanb** [comment]
Thanks so much, building a new conda package now.
