### ISSUE TITLE
GC overhead limit exceeded

### ISSUE THREAD

**Issue by zyywmy** [AstraZeneca-NGS/VarDictJava#80]
When I run VardictJava/build/install/VarDict/bin/VarDict, some jobs were failed due to the memory issue. The error is below. How to fix this issue? Thanks,

Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.regex.Pattern.closure(Pattern.java:3119)
        at java.util.regex.Pattern.group0(Pattern.java:2912)
        at java.util.regex.Pattern.sequence(Pattern.java:2051)
        at java.util.regex.Pattern.expr(Pattern.java:1996)
        at java.util.regex.Pattern.group0(Pattern.java:2905)
        at java.util.regex.Pattern.sequence(Pattern.java:2051)
        at java.util.regex.Pattern.expr(Pattern.java:1996)
        at java.util.regex.Pattern.compile(Pattern.java:1696)
        at java.util.regex.Pattern.<init>(Pattern.java:1351)
        at java.util.regex.Pattern.compile(Pattern.java:1028)
        at com.astrazeneca.vardict.VarDict.findMSI(VarDict.java:3239)
        at com.astrazeneca.vardict.VarDict.toVars(VarDict.java:3029)
        at com.astrazeneca.vardict.VarDict.somaticNotParallel(VarDict.java:362)
        at com.astrazeneca.vardict.VarDict.nonAmpVardict(VarDict.java:258)
        at com.astrazeneca.vardict.VarDict.start(VarDict.java:74)
        at com.astrazeneca.vardict.Main.run(Main.java:134)
        at com.astrazeneca.vardict.Main.main(Main.java:25)

**Comment by nkarulin** [comment]
@zyywmy, what BED file do you use?
VarDict uses memory linear to individual segment size in BED file. So a very huge segment in BAM will require too much memory and likely will cause OutOfMemoryError.

If huge segment is the reason, you could fix it by splitting segment on smaller ones.
Another variant is to give JVM more memory by setting `VAR_DICT_OPTS` environment variable, or changing `DEFAULT_JVM_OPTS` variable in VardictJava/build/install/VarDict/bin/VarDict script. `-Xmx768m` JVM option sets heap size to 768 Mbytes, you could change it for example to `-Xmx4g` to give JVM 4Gb of RAM, or even more depends on your environment.

**Comment by PolinaBevad** [comment]
@zyywmy, hello!
I will close the issue because there was no response from you. The proposed solution must help with this error. If the error still appears, please reopen the issue.
