### ISSUE TITLE
Malformed query

### ISSUE THREAD

**Issue by ExpressionAnalysis** [AstraZeneca-NGS/VarDictJava#87]
I'm getting this error and I need some help figuring out what's wrong with my bam file.  No read has this start position.  Any pointers would be greatly appreciated. Thanks
java.util.concurrent.ExecutionException: htsjdk.samtools.SAMException: Malformed query; start point 27662 lies after end point 0
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.astrazeneca.vardict.VarDict.ampVardictParallel(VarDict.java:5595)
        at com.astrazeneca.vardict.VarDict.start(VarDict.java:86)
        at com.astrazeneca.vardict.Main.run(Main.java:134)
        at com.astrazeneca.vardict.Main.main(Main.java:25)
Caused by: htsjdk.samtools.SAMException: Malformed query; start point 27662 lies after end point 0
        at htsjdk.samtools.reference.IndexedFastaSequenceFile.getSubsequenceAt(IndexedFastaSequenceFile.java:215)
        at com.astrazeneca.vardict.VarDict.retriveSubSeq(VarDict.java:1056)
        at com.astrazeneca.vardict.VarDict.getREF(VarDict.java:3258)
        at com.astrazeneca.vardict.VarDict$ToVarsWorker.call(VarDict.java:5441)
        at com.astrazeneca.vardict.VarDict$AmpVardictWorker.call(VarDict.java:5525)
        at com.astrazeneca.vardict.VarDict$AmpVardictWorker.call(VarDict.java:5506)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by mjafin** [comment]
Hi @ExpressionAnalysis, sorry about the problem you're experiencing. It would help us help you if you let us know the command you're using to call VarDictJava as well as a sample of your bed and bam files.

**Comment by nkarulin** [comment]
@ExpressionAnalysis, there is no read, which has this start position, because the error happens during reference query, not BAM.
Such an exception could happen if your BAM does not contain `@SQ` field in its header with value of your region's chromosome. That is because VarDict have takes information about chromosomes length from BAM header, and if there is no given sequence in header, VarDict put 0 as end of region which leads to the error. 
The same exception stacktrace is in the https://github.com/AstraZeneca-NGS/VarDictJava/issues/89, except the fact that there is multi-threaded launch. Both issue look like the same problem.

Please be sure, your BAM has `@SQ` fields with length for all chromosomes from your BED in its header and please tell if it is the case.

**Comment by PolinaBevad** [comment]
@ExpressionAnalysis, hello!
The same error can occur if you use wrong fasta (not the one to BAM was aligned) and the part of BAM will lie after the end of the chromosome. 
Since there is no reply from you on the last comment, I will close this issue, but you can reopen it if you have any questions about this topic.
